// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: ADILAOJIMPO.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ADILAOJIMPO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HIPAMHDLBDB []RogueUnlockFunctionType `protobuf:"varint,9,rep,packed,name=HIPAMHDLBDB,proto3,enum=RogueUnlockFunctionType" json:"HIPAMHDLBDB,omitempty"`
}

func (x *ADILAOJIMPO) Reset() {
	*x = ADILAOJIMPO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ADILAOJIMPO_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ADILAOJIMPO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ADILAOJIMPO) ProtoMessage() {}

func (x *ADILAOJIMPO) ProtoReflect() protoreflect.Message {
	mi := &file_ADILAOJIMPO_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ADILAOJIMPO.ProtoReflect.Descriptor instead.
func (*ADILAOJIMPO) Descriptor() ([]byte, []int) {
	return file_ADILAOJIMPO_proto_rawDescGZIP(), []int{0}
}

func (x *ADILAOJIMPO) GetHIPAMHDLBDB() []RogueUnlockFunctionType {
	if x != nil {
		return x.HIPAMHDLBDB
	}
	return nil
}

var File_ADILAOJIMPO_proto protoreflect.FileDescriptor

var file_ADILAOJIMPO_proto_rawDesc = []byte{
	0x0a, 0x11, 0x41, 0x44, 0x49, 0x4c, 0x41, 0x4f, 0x4a, 0x49, 0x4d, 0x50, 0x4f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x52, 0x6f, 0x67, 0x75, 0x65, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b,
	0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x49, 0x0a, 0x0b, 0x41, 0x44, 0x49, 0x4c, 0x41, 0x4f, 0x4a, 0x49, 0x4d, 0x50,
	0x4f, 0x12, 0x3a, 0x0a, 0x0b, 0x48, 0x49, 0x50, 0x41, 0x4d, 0x48, 0x44, 0x4c, 0x42, 0x44, 0x42,
	0x18, 0x09, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x52, 0x6f, 0x67, 0x75, 0x65, 0x55, 0x6e,
	0x6c, 0x6f, 0x63, 0x6b, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0b, 0x48, 0x49, 0x50, 0x41, 0x4d, 0x48, 0x44, 0x4c, 0x42, 0x44, 0x42, 0x42, 0x2e, 0x5a,
	0x0e, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xaa,
	0x02, 0x1b, 0x45, 0x67, 0x67, 0x4c, 0x69, 0x6e, 0x6b, 0x2e, 0x44, 0x61, 0x6e, 0x68, 0x65, 0x6e,
	0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ADILAOJIMPO_proto_rawDescOnce sync.Once
	file_ADILAOJIMPO_proto_rawDescData = file_ADILAOJIMPO_proto_rawDesc
)

func file_ADILAOJIMPO_proto_rawDescGZIP() []byte {
	file_ADILAOJIMPO_proto_rawDescOnce.Do(func() {
		file_ADILAOJIMPO_proto_rawDescData = protoimpl.X.CompressGZIP(file_ADILAOJIMPO_proto_rawDescData)
	})
	return file_ADILAOJIMPO_proto_rawDescData
}

var file_ADILAOJIMPO_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ADILAOJIMPO_proto_goTypes = []interface{}{
	(*ADILAOJIMPO)(nil),          // 0: ADILAOJIMPO
	(RogueUnlockFunctionType)(0), // 1: RogueUnlockFunctionType
}
var file_ADILAOJIMPO_proto_depIdxs = []int32{
	1, // 0: ADILAOJIMPO.HIPAMHDLBDB:type_name -> RogueUnlockFunctionType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ADILAOJIMPO_proto_init() }
func file_ADILAOJIMPO_proto_init() {
	if File_ADILAOJIMPO_proto != nil {
		return
	}
	file_RogueUnlockFunctionType_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ADILAOJIMPO_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ADILAOJIMPO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ADILAOJIMPO_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ADILAOJIMPO_proto_goTypes,
		DependencyIndexes: file_ADILAOJIMPO_proto_depIdxs,
		MessageInfos:      file_ADILAOJIMPO_proto_msgTypes,
	}.Build()
	File_ADILAOJIMPO_proto = out.File
	file_ADILAOJIMPO_proto_rawDesc = nil
	file_ADILAOJIMPO_proto_goTypes = nil
	file_ADILAOJIMPO_proto_depIdxs = nil
}
