// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: AEMMBHNPCED.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AEMMBHNPCED struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KIOKEJFGAIE uint32            `protobuf:"varint,5,opt,name=KIOKEJFGAIE,proto3" json:"KIOKEJFGAIE,omitempty"`
	FEJFEGLKAOE map[uint32]uint32 `protobuf:"bytes,4,rep,name=FEJFEGLKAOE,proto3" json:"FEJFEGLKAOE,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	EJOMPJJLHID uint32            `protobuf:"varint,11,opt,name=EJOMPJJLHID,proto3" json:"EJOMPJJLHID,omitempty"`
}

func (x *AEMMBHNPCED) Reset() {
	*x = AEMMBHNPCED{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AEMMBHNPCED_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AEMMBHNPCED) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AEMMBHNPCED) ProtoMessage() {}

func (x *AEMMBHNPCED) ProtoReflect() protoreflect.Message {
	mi := &file_AEMMBHNPCED_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AEMMBHNPCED.ProtoReflect.Descriptor instead.
func (*AEMMBHNPCED) Descriptor() ([]byte, []int) {
	return file_AEMMBHNPCED_proto_rawDescGZIP(), []int{0}
}

func (x *AEMMBHNPCED) GetKIOKEJFGAIE() uint32 {
	if x != nil {
		return x.KIOKEJFGAIE
	}
	return 0
}

func (x *AEMMBHNPCED) GetFEJFEGLKAOE() map[uint32]uint32 {
	if x != nil {
		return x.FEJFEGLKAOE
	}
	return nil
}

func (x *AEMMBHNPCED) GetEJOMPJJLHID() uint32 {
	if x != nil {
		return x.EJOMPJJLHID
	}
	return 0
}

var File_AEMMBHNPCED_proto protoreflect.FileDescriptor

var file_AEMMBHNPCED_proto_rawDesc = []byte{
	0x0a, 0x11, 0x41, 0x45, 0x4d, 0x4d, 0x42, 0x48, 0x4e, 0x50, 0x43, 0x45, 0x44, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xd2, 0x01, 0x0a, 0x0b, 0x41, 0x45, 0x4d, 0x4d, 0x42, 0x48, 0x4e, 0x50,
	0x43, 0x45, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x4b, 0x49, 0x4f, 0x4b, 0x45, 0x4a, 0x46, 0x47, 0x41,
	0x49, 0x45, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x4b, 0x49, 0x4f, 0x4b, 0x45, 0x4a,
	0x46, 0x47, 0x41, 0x49, 0x45, 0x12, 0x3f, 0x0a, 0x0b, 0x46, 0x45, 0x4a, 0x46, 0x45, 0x47, 0x4c,
	0x4b, 0x41, 0x4f, 0x45, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x41, 0x45, 0x4d,
	0x4d, 0x42, 0x48, 0x4e, 0x50, 0x43, 0x45, 0x44, 0x2e, 0x46, 0x45, 0x4a, 0x46, 0x45, 0x47, 0x4c,
	0x4b, 0x41, 0x4f, 0x45, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x46, 0x45, 0x4a, 0x46, 0x45,
	0x47, 0x4c, 0x4b, 0x41, 0x4f, 0x45, 0x12, 0x20, 0x0a, 0x0b, 0x45, 0x4a, 0x4f, 0x4d, 0x50, 0x4a,
	0x4a, 0x4c, 0x48, 0x49, 0x44, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x45, 0x4a, 0x4f,
	0x4d, 0x50, 0x4a, 0x4a, 0x4c, 0x48, 0x49, 0x44, 0x1a, 0x3e, 0x0a, 0x10, 0x46, 0x45, 0x4a, 0x46,
	0x45, 0x47, 0x4c, 0x4b, 0x41, 0x4f, 0x45, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x28, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x1b, 0x45, 0x67, 0x67, 0x4c, 0x69, 0x6e, 0x6b, 0x2e, 0x44,
	0x61, 0x6e, 0x68, 0x65, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_AEMMBHNPCED_proto_rawDescOnce sync.Once
	file_AEMMBHNPCED_proto_rawDescData = file_AEMMBHNPCED_proto_rawDesc
)

func file_AEMMBHNPCED_proto_rawDescGZIP() []byte {
	file_AEMMBHNPCED_proto_rawDescOnce.Do(func() {
		file_AEMMBHNPCED_proto_rawDescData = protoimpl.X.CompressGZIP(file_AEMMBHNPCED_proto_rawDescData)
	})
	return file_AEMMBHNPCED_proto_rawDescData
}

var file_AEMMBHNPCED_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_AEMMBHNPCED_proto_goTypes = []interface{}{
	(*AEMMBHNPCED)(nil), // 0: AEMMBHNPCED
	nil,                 // 1: AEMMBHNPCED.FEJFEGLKAOEEntry
}
var file_AEMMBHNPCED_proto_depIdxs = []int32{
	1, // 0: AEMMBHNPCED.FEJFEGLKAOE:type_name -> AEMMBHNPCED.FEJFEGLKAOEEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_AEMMBHNPCED_proto_init() }
func file_AEMMBHNPCED_proto_init() {
	if File_AEMMBHNPCED_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_AEMMBHNPCED_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AEMMBHNPCED); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_AEMMBHNPCED_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AEMMBHNPCED_proto_goTypes,
		DependencyIndexes: file_AEMMBHNPCED_proto_depIdxs,
		MessageInfos:      file_AEMMBHNPCED_proto_msgTypes,
	}.Build()
	File_AEMMBHNPCED_proto = out.File
	file_AEMMBHNPCED_proto_rawDesc = nil
	file_AEMMBHNPCED_proto_goTypes = nil
	file_AEMMBHNPCED_proto_depIdxs = nil
}
