// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: AetherDivideSpiritExpUpCsReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AetherDivideSpiritExpUpCsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ACOICEJEEJI uint32 `protobuf:"varint,8,opt,name=ACOICEJEEJI,proto3" json:"ACOICEJEEJI,omitempty"`
	HLHDEHNIMOO uint32 `protobuf:"varint,5,opt,name=HLHDEHNIMOO,proto3" json:"HLHDEHNIMOO,omitempty"`
	MPLCMPDGHMF uint32 `protobuf:"varint,6,opt,name=MPLCMPDGHMF,proto3" json:"MPLCMPDGHMF,omitempty"`
}

func (x *AetherDivideSpiritExpUpCsReq) Reset() {
	*x = AetherDivideSpiritExpUpCsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AetherDivideSpiritExpUpCsReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AetherDivideSpiritExpUpCsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AetherDivideSpiritExpUpCsReq) ProtoMessage() {}

func (x *AetherDivideSpiritExpUpCsReq) ProtoReflect() protoreflect.Message {
	mi := &file_AetherDivideSpiritExpUpCsReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AetherDivideSpiritExpUpCsReq.ProtoReflect.Descriptor instead.
func (*AetherDivideSpiritExpUpCsReq) Descriptor() ([]byte, []int) {
	return file_AetherDivideSpiritExpUpCsReq_proto_rawDescGZIP(), []int{0}
}

func (x *AetherDivideSpiritExpUpCsReq) GetACOICEJEEJI() uint32 {
	if x != nil {
		return x.ACOICEJEEJI
	}
	return 0
}

func (x *AetherDivideSpiritExpUpCsReq) GetHLHDEHNIMOO() uint32 {
	if x != nil {
		return x.HLHDEHNIMOO
	}
	return 0
}

func (x *AetherDivideSpiritExpUpCsReq) GetMPLCMPDGHMF() uint32 {
	if x != nil {
		return x.MPLCMPDGHMF
	}
	return 0
}

var File_AetherDivideSpiritExpUpCsReq_proto protoreflect.FileDescriptor

var file_AetherDivideSpiritExpUpCsReq_proto_rawDesc = []byte{
	0x0a, 0x22, 0x41, 0x65, 0x74, 0x68, 0x65, 0x72, 0x44, 0x69, 0x76, 0x69, 0x64, 0x65, 0x53, 0x70,
	0x69, 0x72, 0x69, 0x74, 0x45, 0x78, 0x70, 0x55, 0x70, 0x43, 0x73, 0x52, 0x65, 0x71, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x84, 0x01, 0x0a, 0x1c, 0x41, 0x65, 0x74, 0x68, 0x65, 0x72, 0x44,
	0x69, 0x76, 0x69, 0x64, 0x65, 0x53, 0x70, 0x69, 0x72, 0x69, 0x74, 0x45, 0x78, 0x70, 0x55, 0x70,
	0x43, 0x73, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x43, 0x4f, 0x49, 0x43, 0x45, 0x4a,
	0x45, 0x45, 0x4a, 0x49, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x41, 0x43, 0x4f, 0x49,
	0x43, 0x45, 0x4a, 0x45, 0x45, 0x4a, 0x49, 0x12, 0x20, 0x0a, 0x0b, 0x48, 0x4c, 0x48, 0x44, 0x45,
	0x48, 0x4e, 0x49, 0x4d, 0x4f, 0x4f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x48, 0x4c,
	0x48, 0x44, 0x45, 0x48, 0x4e, 0x49, 0x4d, 0x4f, 0x4f, 0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x50, 0x4c,
	0x43, 0x4d, 0x50, 0x44, 0x47, 0x48, 0x4d, 0x46, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x4d, 0x50, 0x4c, 0x43, 0x4d, 0x50, 0x44, 0x47, 0x48, 0x4d, 0x46, 0x42, 0x28, 0x5a, 0x08, 0x2e,
	0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x1b, 0x45, 0x67, 0x67, 0x4c, 0x69, 0x6e,
	0x6b, 0x2e, 0x44, 0x61, 0x6e, 0x68, 0x65, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_AetherDivideSpiritExpUpCsReq_proto_rawDescOnce sync.Once
	file_AetherDivideSpiritExpUpCsReq_proto_rawDescData = file_AetherDivideSpiritExpUpCsReq_proto_rawDesc
)

func file_AetherDivideSpiritExpUpCsReq_proto_rawDescGZIP() []byte {
	file_AetherDivideSpiritExpUpCsReq_proto_rawDescOnce.Do(func() {
		file_AetherDivideSpiritExpUpCsReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_AetherDivideSpiritExpUpCsReq_proto_rawDescData)
	})
	return file_AetherDivideSpiritExpUpCsReq_proto_rawDescData
}

var file_AetherDivideSpiritExpUpCsReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_AetherDivideSpiritExpUpCsReq_proto_goTypes = []interface{}{
	(*AetherDivideSpiritExpUpCsReq)(nil), // 0: AetherDivideSpiritExpUpCsReq
}
var file_AetherDivideSpiritExpUpCsReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_AetherDivideSpiritExpUpCsReq_proto_init() }
func file_AetherDivideSpiritExpUpCsReq_proto_init() {
	if File_AetherDivideSpiritExpUpCsReq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_AetherDivideSpiritExpUpCsReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AetherDivideSpiritExpUpCsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_AetherDivideSpiritExpUpCsReq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AetherDivideSpiritExpUpCsReq_proto_goTypes,
		DependencyIndexes: file_AetherDivideSpiritExpUpCsReq_proto_depIdxs,
		MessageInfos:      file_AetherDivideSpiritExpUpCsReq_proto_msgTypes,
	}.Build()
	File_AetherDivideSpiritExpUpCsReq_proto = out.File
	file_AetherDivideSpiritExpUpCsReq_proto_rawDesc = nil
	file_AetherDivideSpiritExpUpCsReq_proto_goTypes = nil
	file_AetherDivideSpiritExpUpCsReq_proto_depIdxs = nil
}
