// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: BDNPDDODDBF.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BDNPDDODDBF struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IJODDPFHNGA uint32         `protobuf:"varint,8,opt,name=IJODDPFHNGA,proto3" json:"IJODDPFHNGA,omitempty"`
	CCPGNMCLGBD []*AFAOCELKGMN `protobuf:"bytes,1,rep,name=CCPGNMCLGBD,proto3" json:"CCPGNMCLGBD,omitempty"`
	MapId       uint32         `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
}

func (x *BDNPDDODDBF) Reset() {
	*x = BDNPDDODDBF{}
	if protoimpl.UnsafeEnabled {
		mi := &file_BDNPDDODDBF_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BDNPDDODDBF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BDNPDDODDBF) ProtoMessage() {}

func (x *BDNPDDODDBF) ProtoReflect() protoreflect.Message {
	mi := &file_BDNPDDODDBF_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BDNPDDODDBF.ProtoReflect.Descriptor instead.
func (*BDNPDDODDBF) Descriptor() ([]byte, []int) {
	return file_BDNPDDODDBF_proto_rawDescGZIP(), []int{0}
}

func (x *BDNPDDODDBF) GetIJODDPFHNGA() uint32 {
	if x != nil {
		return x.IJODDPFHNGA
	}
	return 0
}

func (x *BDNPDDODDBF) GetCCPGNMCLGBD() []*AFAOCELKGMN {
	if x != nil {
		return x.CCPGNMCLGBD
	}
	return nil
}

func (x *BDNPDDODDBF) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

var File_BDNPDDODDBF_proto protoreflect.FileDescriptor

var file_BDNPDDODDBF_proto_rawDesc = []byte{
	0x0a, 0x11, 0x42, 0x44, 0x4e, 0x50, 0x44, 0x44, 0x4f, 0x44, 0x44, 0x42, 0x46, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x41, 0x46, 0x41, 0x4f, 0x43, 0x45, 0x4c, 0x4b, 0x47, 0x4d, 0x4e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x76, 0x0a, 0x0b, 0x42, 0x44, 0x4e, 0x50, 0x44, 0x44,
	0x4f, 0x44, 0x44, 0x42, 0x46, 0x12, 0x20, 0x0a, 0x0b, 0x49, 0x4a, 0x4f, 0x44, 0x44, 0x50, 0x46,
	0x48, 0x4e, 0x47, 0x41, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x49, 0x4a, 0x4f, 0x44,
	0x44, 0x50, 0x46, 0x48, 0x4e, 0x47, 0x41, 0x12, 0x2e, 0x0a, 0x0b, 0x43, 0x43, 0x50, 0x47, 0x4e,
	0x4d, 0x43, 0x4c, 0x47, 0x42, 0x44, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x41,
	0x46, 0x41, 0x4f, 0x43, 0x45, 0x4c, 0x4b, 0x47, 0x4d, 0x4e, 0x52, 0x0b, 0x43, 0x43, 0x50, 0x47,
	0x4e, 0x4d, 0x43, 0x4c, 0x47, 0x42, 0x44, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x61, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x42, 0x0a,
	0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_BDNPDDODDBF_proto_rawDescOnce sync.Once
	file_BDNPDDODDBF_proto_rawDescData = file_BDNPDDODDBF_proto_rawDesc
)

func file_BDNPDDODDBF_proto_rawDescGZIP() []byte {
	file_BDNPDDODDBF_proto_rawDescOnce.Do(func() {
		file_BDNPDDODDBF_proto_rawDescData = protoimpl.X.CompressGZIP(file_BDNPDDODDBF_proto_rawDescData)
	})
	return file_BDNPDDODDBF_proto_rawDescData
}

var file_BDNPDDODDBF_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_BDNPDDODDBF_proto_goTypes = []interface{}{
	(*BDNPDDODDBF)(nil), // 0: BDNPDDODDBF
	(*AFAOCELKGMN)(nil), // 1: AFAOCELKGMN
}
var file_BDNPDDODDBF_proto_depIdxs = []int32{
	1, // 0: BDNPDDODDBF.CCPGNMCLGBD:type_name -> AFAOCELKGMN
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_BDNPDDODDBF_proto_init() }
func file_BDNPDDODDBF_proto_init() {
	if File_BDNPDDODDBF_proto != nil {
		return
	}
	file_AFAOCELKGMN_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_BDNPDDODDBF_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BDNPDDODDBF); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_BDNPDDODDBF_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_BDNPDDODDBF_proto_goTypes,
		DependencyIndexes: file_BDNPDDODDBF_proto_depIdxs,
		MessageInfos:      file_BDNPDDODDBF_proto_msgTypes,
	}.Build()
	File_BDNPDDODDBF_proto = out.File
	file_BDNPDDODDBF_proto_rawDesc = nil
	file_BDNPDDODDBF_proto_goTypes = nil
	file_BDNPDDODDBF_proto_depIdxs = nil
}
