// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: BNCBGBEGCAD.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BNCBGBEGCAD struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level       uint32         `protobuf:"varint,11,opt,name=level,proto3" json:"level,omitempty"`
	KKOAFEMMGJK uint32         `protobuf:"varint,10,opt,name=KKOAFEMMGJK,proto3" json:"KKOAFEMMGJK,omitempty"`
	HOPIAJAGJNN uint32         `protobuf:"varint,6,opt,name=HOPIAJAGJNN,proto3" json:"HOPIAJAGJNN,omitempty"`
	BDJFEMMEEPB uint32         `protobuf:"varint,5,opt,name=BDJFEMMEEPB,proto3" json:"BDJFEMMEEPB,omitempty"`
	LFBGDGOICHA []*FENNLIFPBGP `protobuf:"bytes,7,rep,name=LFBGDGOICHA,proto3" json:"LFBGDGOICHA,omitempty"`
	AreaId      uint32         `protobuf:"varint,1,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
}

func (x *BNCBGBEGCAD) Reset() {
	*x = BNCBGBEGCAD{}
	if protoimpl.UnsafeEnabled {
		mi := &file_BNCBGBEGCAD_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BNCBGBEGCAD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BNCBGBEGCAD) ProtoMessage() {}

func (x *BNCBGBEGCAD) ProtoReflect() protoreflect.Message {
	mi := &file_BNCBGBEGCAD_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BNCBGBEGCAD.ProtoReflect.Descriptor instead.
func (*BNCBGBEGCAD) Descriptor() ([]byte, []int) {
	return file_BNCBGBEGCAD_proto_rawDescGZIP(), []int{0}
}

func (x *BNCBGBEGCAD) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *BNCBGBEGCAD) GetKKOAFEMMGJK() uint32 {
	if x != nil {
		return x.KKOAFEMMGJK
	}
	return 0
}

func (x *BNCBGBEGCAD) GetHOPIAJAGJNN() uint32 {
	if x != nil {
		return x.HOPIAJAGJNN
	}
	return 0
}

func (x *BNCBGBEGCAD) GetBDJFEMMEEPB() uint32 {
	if x != nil {
		return x.BDJFEMMEEPB
	}
	return 0
}

func (x *BNCBGBEGCAD) GetLFBGDGOICHA() []*FENNLIFPBGP {
	if x != nil {
		return x.LFBGDGOICHA
	}
	return nil
}

func (x *BNCBGBEGCAD) GetAreaId() uint32 {
	if x != nil {
		return x.AreaId
	}
	return 0
}

var File_BNCBGBEGCAD_proto protoreflect.FileDescriptor

var file_BNCBGBEGCAD_proto_rawDesc = []byte{
	0x0a, 0x11, 0x42, 0x4e, 0x43, 0x42, 0x47, 0x42, 0x45, 0x47, 0x43, 0x41, 0x44, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x46, 0x45, 0x4e, 0x4e, 0x4c, 0x49, 0x46, 0x50, 0x42, 0x47, 0x50,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd2, 0x01, 0x0a, 0x0b, 0x42, 0x4e, 0x43, 0x42, 0x47,
	0x42, 0x45, 0x47, 0x43, 0x41, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x20, 0x0a, 0x0b,
	0x4b, 0x4b, 0x4f, 0x41, 0x46, 0x45, 0x4d, 0x4d, 0x47, 0x4a, 0x4b, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0b, 0x4b, 0x4b, 0x4f, 0x41, 0x46, 0x45, 0x4d, 0x4d, 0x47, 0x4a, 0x4b, 0x12, 0x20,
	0x0a, 0x0b, 0x48, 0x4f, 0x50, 0x49, 0x41, 0x4a, 0x41, 0x47, 0x4a, 0x4e, 0x4e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0b, 0x48, 0x4f, 0x50, 0x49, 0x41, 0x4a, 0x41, 0x47, 0x4a, 0x4e, 0x4e,
	0x12, 0x20, 0x0a, 0x0b, 0x42, 0x44, 0x4a, 0x46, 0x45, 0x4d, 0x4d, 0x45, 0x45, 0x50, 0x42, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x42, 0x44, 0x4a, 0x46, 0x45, 0x4d, 0x4d, 0x45, 0x45,
	0x50, 0x42, 0x12, 0x2e, 0x0a, 0x0b, 0x4c, 0x46, 0x42, 0x47, 0x44, 0x47, 0x4f, 0x49, 0x43, 0x48,
	0x41, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x46, 0x45, 0x4e, 0x4e, 0x4c, 0x49,
	0x46, 0x50, 0x42, 0x47, 0x50, 0x52, 0x0b, 0x4c, 0x46, 0x42, 0x47, 0x44, 0x47, 0x4f, 0x49, 0x43,
	0x48, 0x41, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x72, 0x65, 0x61, 0x49, 0x64, 0x42, 0x28, 0x5a, 0x08, 0x2e,
	0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x1b, 0x45, 0x67, 0x67, 0x4c, 0x69, 0x6e,
	0x6b, 0x2e, 0x44, 0x61, 0x6e, 0x68, 0x65, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_BNCBGBEGCAD_proto_rawDescOnce sync.Once
	file_BNCBGBEGCAD_proto_rawDescData = file_BNCBGBEGCAD_proto_rawDesc
)

func file_BNCBGBEGCAD_proto_rawDescGZIP() []byte {
	file_BNCBGBEGCAD_proto_rawDescOnce.Do(func() {
		file_BNCBGBEGCAD_proto_rawDescData = protoimpl.X.CompressGZIP(file_BNCBGBEGCAD_proto_rawDescData)
	})
	return file_BNCBGBEGCAD_proto_rawDescData
}

var file_BNCBGBEGCAD_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_BNCBGBEGCAD_proto_goTypes = []interface{}{
	(*BNCBGBEGCAD)(nil), // 0: BNCBGBEGCAD
	(*FENNLIFPBGP)(nil), // 1: FENNLIFPBGP
}
var file_BNCBGBEGCAD_proto_depIdxs = []int32{
	1, // 0: BNCBGBEGCAD.LFBGDGOICHA:type_name -> FENNLIFPBGP
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_BNCBGBEGCAD_proto_init() }
func file_BNCBGBEGCAD_proto_init() {
	if File_BNCBGBEGCAD_proto != nil {
		return
	}
	file_FENNLIFPBGP_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_BNCBGBEGCAD_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BNCBGBEGCAD); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_BNCBGBEGCAD_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_BNCBGBEGCAD_proto_goTypes,
		DependencyIndexes: file_BNCBGBEGCAD_proto_depIdxs,
		MessageInfos:      file_BNCBGBEGCAD_proto_msgTypes,
	}.Build()
	File_BNCBGBEGCAD_proto = out.File
	file_BNCBGBEGCAD_proto_rawDesc = nil
	file_BNCBGBEGCAD_proto_goTypes = nil
	file_BNCBGBEGCAD_proto_depIdxs = nil
}
