// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: ChallengeStoryInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChallengeStoryInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurStoryBuff *ChallengeStoryBuffInfo `protobuf:"bytes,10,opt,name=cur_story_buff,json=curStoryBuff,proto3" json:"cur_story_buff,omitempty"`
	CurBossBuff  *ChallengeBossBuffInfo  `protobuf:"bytes,2,opt,name=cur_boss_buff,json=curBossBuff,proto3" json:"cur_boss_buff,omitempty"`
}

func (x *ChallengeStoryInfo) Reset() {
	*x = ChallengeStoryInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChallengeStoryInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChallengeStoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeStoryInfo) ProtoMessage() {}

func (x *ChallengeStoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ChallengeStoryInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeStoryInfo.ProtoReflect.Descriptor instead.
func (*ChallengeStoryInfo) Descriptor() ([]byte, []int) {
	return file_ChallengeStoryInfo_proto_rawDescGZIP(), []int{0}
}

func (x *ChallengeStoryInfo) GetCurStoryBuff() *ChallengeStoryBuffInfo {
	if x != nil {
		return x.CurStoryBuff
	}
	return nil
}

func (x *ChallengeStoryInfo) GetCurBossBuff() *ChallengeBossBuffInfo {
	if x != nil {
		return x.CurBossBuff
	}
	return nil
}

var File_ChallengeStoryInfo_proto protoreflect.FileDescriptor

var file_ChallengeStoryInfo_proto_rawDesc = []byte{
	0x0a, 0x18, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x79,
	0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x43, 0x68, 0x61, 0x6c,
	0x6c, 0x65, 0x6e, 0x67, 0x65, 0x42, 0x6f, 0x73, 0x73, 0x42, 0x75, 0x66, 0x66, 0x49, 0x6e, 0x66,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e,
	0x67, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x42, 0x75, 0x66, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8f, 0x01, 0x0a, 0x12, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65,
	0x6e, 0x67, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3d, 0x0a, 0x0e,
	0x63, 0x75, 0x72, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x62, 0x75, 0x66, 0x66, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65,
	0x53, 0x74, 0x6f, 0x72, 0x79, 0x42, 0x75, 0x66, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x63,
	0x75, 0x72, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x42, 0x75, 0x66, 0x66, 0x12, 0x3a, 0x0a, 0x0d, 0x63,
	0x75, 0x72, 0x5f, 0x62, 0x6f, 0x73, 0x73, 0x5f, 0x62, 0x75, 0x66, 0x66, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x42, 0x6f,
	0x73, 0x73, 0x42, 0x75, 0x66, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x42,
	0x6f, 0x73, 0x73, 0x42, 0x75, 0x66, 0x66, 0x42, 0x28, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x1b, 0x45, 0x67, 0x67, 0x4c, 0x69, 0x6e, 0x6b, 0x2e, 0x44, 0x61,
	0x6e, 0x68, 0x65, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ChallengeStoryInfo_proto_rawDescOnce sync.Once
	file_ChallengeStoryInfo_proto_rawDescData = file_ChallengeStoryInfo_proto_rawDesc
)

func file_ChallengeStoryInfo_proto_rawDescGZIP() []byte {
	file_ChallengeStoryInfo_proto_rawDescOnce.Do(func() {
		file_ChallengeStoryInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_ChallengeStoryInfo_proto_rawDescData)
	})
	return file_ChallengeStoryInfo_proto_rawDescData
}

var file_ChallengeStoryInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ChallengeStoryInfo_proto_goTypes = []interface{}{
	(*ChallengeStoryInfo)(nil),     // 0: ChallengeStoryInfo
	(*ChallengeStoryBuffInfo)(nil), // 1: ChallengeStoryBuffInfo
	(*ChallengeBossBuffInfo)(nil),  // 2: ChallengeBossBuffInfo
}
var file_ChallengeStoryInfo_proto_depIdxs = []int32{
	1, // 0: ChallengeStoryInfo.cur_story_buff:type_name -> ChallengeStoryBuffInfo
	2, // 1: ChallengeStoryInfo.cur_boss_buff:type_name -> ChallengeBossBuffInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ChallengeStoryInfo_proto_init() }
func file_ChallengeStoryInfo_proto_init() {
	if File_ChallengeStoryInfo_proto != nil {
		return
	}
	file_ChallengeBossBuffInfo_proto_init()
	file_ChallengeStoryBuffInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ChallengeStoryInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChallengeStoryInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ChallengeStoryInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ChallengeStoryInfo_proto_goTypes,
		DependencyIndexes: file_ChallengeStoryInfo_proto_depIdxs,
		MessageInfos:      file_ChallengeStoryInfo_proto_msgTypes,
	}.Build()
	File_ChallengeStoryInfo_proto = out.File
	file_ChallengeStoryInfo_proto_rawDesc = nil
	file_ChallengeStoryInfo_proto_goTypes = nil
	file_ChallengeStoryInfo_proto_depIdxs = nil
}
