// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: ChallengeStageTertinggi.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChallengeStageTertinggi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level             uint32                 `protobuf:"varint,12,opt,name=level,proto3" json:"level,omitempty"`
	BattleRecordStars uint32                 `protobuf:"varint,6,opt,name=battle_record_stars,json=battleRecordStars,proto3" json:"battle_record_stars,omitempty"`
	RoundCount        uint32                 `protobuf:"varint,8,opt,name=round_count,json=roundCount,proto3" json:"round_count,omitempty"`
	LineupList        []*ChallengeLineupList `protobuf:"bytes,11,rep,name=lineup_list,json=lineupList,proto3" json:"lineup_list,omitempty"`
}

func (x *ChallengeStageTertinggi) Reset() {
	*x = ChallengeStageTertinggi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChallengeStageTertinggi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChallengeStageTertinggi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeStageTertinggi) ProtoMessage() {}

func (x *ChallengeStageTertinggi) ProtoReflect() protoreflect.Message {
	mi := &file_ChallengeStageTertinggi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeStageTertinggi.ProtoReflect.Descriptor instead.
func (*ChallengeStageTertinggi) Descriptor() ([]byte, []int) {
	return file_ChallengeStageTertinggi_proto_rawDescGZIP(), []int{0}
}

func (x *ChallengeStageTertinggi) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ChallengeStageTertinggi) GetBattleRecordStars() uint32 {
	if x != nil {
		return x.BattleRecordStars
	}
	return 0
}

func (x *ChallengeStageTertinggi) GetRoundCount() uint32 {
	if x != nil {
		return x.RoundCount
	}
	return 0
}

func (x *ChallengeStageTertinggi) GetLineupList() []*ChallengeLineupList {
	if x != nil {
		return x.LineupList
	}
	return nil
}

var File_ChallengeStageTertinggi_proto protoreflect.FileDescriptor

var file_ChallengeStageTertinggi_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x54, 0x65, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x67, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x19, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x75, 0x70,
	0x4c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb7, 0x01, 0x0a, 0x17, 0x43,
	0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x53, 0x74, 0x61, 0x67, 0x65, 0x54, 0x65, 0x72,
	0x74, 0x69, 0x6e, 0x67, 0x67, 0x69, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x2e, 0x0a, 0x13,
	0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x73, 0x74,
	0x61, 0x72, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x62, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53, 0x74, 0x61, 0x72, 0x73, 0x12, 0x1f, 0x0a, 0x0b,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x35, 0x0a,
	0x0b, 0x6c, 0x69, 0x6e, 0x65, 0x75, 0x70, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x0b, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x4c, 0x69,
	0x6e, 0x65, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0a, 0x6c, 0x69, 0x6e, 0x65, 0x75, 0x70,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x2e, 0x5a, 0x0e, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x1b, 0x45, 0x67, 0x67, 0x4c, 0x69, 0x6e, 0x6b,
	0x2e, 0x44, 0x61, 0x6e, 0x68, 0x65, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ChallengeStageTertinggi_proto_rawDescOnce sync.Once
	file_ChallengeStageTertinggi_proto_rawDescData = file_ChallengeStageTertinggi_proto_rawDesc
)

func file_ChallengeStageTertinggi_proto_rawDescGZIP() []byte {
	file_ChallengeStageTertinggi_proto_rawDescOnce.Do(func() {
		file_ChallengeStageTertinggi_proto_rawDescData = protoimpl.X.CompressGZIP(file_ChallengeStageTertinggi_proto_rawDescData)
	})
	return file_ChallengeStageTertinggi_proto_rawDescData
}

var file_ChallengeStageTertinggi_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ChallengeStageTertinggi_proto_goTypes = []interface{}{
	(*ChallengeStageTertinggi)(nil), // 0: ChallengeStageTertinggi
	(*ChallengeLineupList)(nil),     // 1: ChallengeLineupList
}
var file_ChallengeStageTertinggi_proto_depIdxs = []int32{
	1, // 0: ChallengeStageTertinggi.lineup_list:type_name -> ChallengeLineupList
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ChallengeStageTertinggi_proto_init() }
func file_ChallengeStageTertinggi_proto_init() {
	if File_ChallengeStageTertinggi_proto != nil {
		return
	}
	file_ChallengeLineupList_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ChallengeStageTertinggi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChallengeStageTertinggi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ChallengeStageTertinggi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ChallengeStageTertinggi_proto_goTypes,
		DependencyIndexes: file_ChallengeStageTertinggi_proto_depIdxs,
		MessageInfos:      file_ChallengeStageTertinggi_proto_msgTypes,
	}.Build()
	File_ChallengeStageTertinggi_proto = out.File
	file_ChallengeStageTertinggi_proto_rawDesc = nil
	file_ChallengeStageTertinggi_proto_goTypes = nil
	file_ChallengeStageTertinggi_proto_depIdxs = nil
}
