// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: ChessRogueCurrentInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChessRogueCurrentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RogueSubMode         uint32           `protobuf:"varint,8,opt,name=rogue_sub_mode,json=rogueSubMode,proto3" json:"rogue_sub_mode,omitempty"`
	RogueCurrentGameInfo []*RogueGameInfo `protobuf:"bytes,9,rep,name=rogue_current_game_info,json=rogueCurrentGameInfo,proto3" json:"rogue_current_game_info,omitempty"`
}

func (x *ChessRogueCurrentInfo) Reset() {
	*x = ChessRogueCurrentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChessRogueCurrentInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChessRogueCurrentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChessRogueCurrentInfo) ProtoMessage() {}

func (x *ChessRogueCurrentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ChessRogueCurrentInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChessRogueCurrentInfo.ProtoReflect.Descriptor instead.
func (*ChessRogueCurrentInfo) Descriptor() ([]byte, []int) {
	return file_ChessRogueCurrentInfo_proto_rawDescGZIP(), []int{0}
}

func (x *ChessRogueCurrentInfo) GetRogueSubMode() uint32 {
	if x != nil {
		return x.RogueSubMode
	}
	return 0
}

func (x *ChessRogueCurrentInfo) GetRogueCurrentGameInfo() []*RogueGameInfo {
	if x != nil {
		return x.RogueCurrentGameInfo
	}
	return nil
}

var File_ChessRogueCurrentInfo_proto protoreflect.FileDescriptor

var file_ChessRogueCurrentInfo_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x43, 0x68, 0x65, 0x73, 0x73, 0x52, 0x6f, 0x67, 0x75, 0x65, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x52,
	0x6f, 0x67, 0x75, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x84, 0x01, 0x0a, 0x15, 0x43, 0x68, 0x65, 0x73, 0x73, 0x52, 0x6f, 0x67, 0x75,
	0x65, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x0a, 0x0e,
	0x72, 0x6f, 0x67, 0x75, 0x65, 0x5f, 0x73, 0x75, 0x62, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x72, 0x6f, 0x67, 0x75, 0x65, 0x53, 0x75, 0x62, 0x4d, 0x6f,
	0x64, 0x65, 0x12, 0x45, 0x0a, 0x17, 0x72, 0x6f, 0x67, 0x75, 0x65, 0x5f, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x09, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x52, 0x6f, 0x67, 0x75, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x14, 0x72, 0x6f, 0x67, 0x75, 0x65, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x2e, 0x5a, 0x0e, 0x2e, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x1b, 0x45, 0x67,
	0x67, 0x4c, 0x69, 0x6e, 0x6b, 0x2e, 0x44, 0x61, 0x6e, 0x68, 0x65, 0x6e, 0x67, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_ChessRogueCurrentInfo_proto_rawDescOnce sync.Once
	file_ChessRogueCurrentInfo_proto_rawDescData = file_ChessRogueCurrentInfo_proto_rawDesc
)

func file_ChessRogueCurrentInfo_proto_rawDescGZIP() []byte {
	file_ChessRogueCurrentInfo_proto_rawDescOnce.Do(func() {
		file_ChessRogueCurrentInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_ChessRogueCurrentInfo_proto_rawDescData)
	})
	return file_ChessRogueCurrentInfo_proto_rawDescData
}

var file_ChessRogueCurrentInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ChessRogueCurrentInfo_proto_goTypes = []interface{}{
	(*ChessRogueCurrentInfo)(nil), // 0: ChessRogueCurrentInfo
	(*RogueGameInfo)(nil),         // 1: RogueGameInfo
}
var file_ChessRogueCurrentInfo_proto_depIdxs = []int32{
	1, // 0: ChessRogueCurrentInfo.rogue_current_game_info:type_name -> RogueGameInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ChessRogueCurrentInfo_proto_init() }
func file_ChessRogueCurrentInfo_proto_init() {
	if File_ChessRogueCurrentInfo_proto != nil {
		return
	}
	file_RogueGameInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ChessRogueCurrentInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChessRogueCurrentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ChessRogueCurrentInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ChessRogueCurrentInfo_proto_goTypes,
		DependencyIndexes: file_ChessRogueCurrentInfo_proto_depIdxs,
		MessageInfos:      file_ChessRogueCurrentInfo_proto_msgTypes,
	}.Build()
	File_ChessRogueCurrentInfo_proto = out.File
	file_ChessRogueCurrentInfo_proto_rawDesc = nil
	file_ChessRogueCurrentInfo_proto_goTypes = nil
	file_ChessRogueCurrentInfo_proto_depIdxs = nil
}
