// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: CLENLGMHIGC.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CLENLGMHIGC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId     uint32       `protobuf:"varint,11,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	IMFNKJKCMMI uint32       `protobuf:"varint,6,opt,name=IMFNKJKCMMI,proto3" json:"IMFNKJKCMMI,omitempty"`
	GNCLJAHHBKO *IHCMPIEKNFB `protobuf:"bytes,2026,opt,name=GNCLJAHHBKO,proto3" json:"GNCLJAHHBKO,omitempty"`
	CDKCNKLPIGJ *JOCGPNELOBK `protobuf:"bytes,1644,opt,name=CDKCNKLPIGJ,proto3" json:"CDKCNKLPIGJ,omitempty"`
	LJBEOGOEJIJ *CEIIKIIFBBB `protobuf:"bytes,826,opt,name=LJBEOGOEJIJ,proto3" json:"LJBEOGOEJIJ,omitempty"`
}

func (x *CLENLGMHIGC) Reset() {
	*x = CLENLGMHIGC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CLENLGMHIGC_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CLENLGMHIGC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLENLGMHIGC) ProtoMessage() {}

func (x *CLENLGMHIGC) ProtoReflect() protoreflect.Message {
	mi := &file_CLENLGMHIGC_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLENLGMHIGC.ProtoReflect.Descriptor instead.
func (*CLENLGMHIGC) Descriptor() ([]byte, []int) {
	return file_CLENLGMHIGC_proto_rawDescGZIP(), []int{0}
}

func (x *CLENLGMHIGC) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CLENLGMHIGC) GetIMFNKJKCMMI() uint32 {
	if x != nil {
		return x.IMFNKJKCMMI
	}
	return 0
}

func (x *CLENLGMHIGC) GetGNCLJAHHBKO() *IHCMPIEKNFB {
	if x != nil {
		return x.GNCLJAHHBKO
	}
	return nil
}

func (x *CLENLGMHIGC) GetCDKCNKLPIGJ() *JOCGPNELOBK {
	if x != nil {
		return x.CDKCNKLPIGJ
	}
	return nil
}

func (x *CLENLGMHIGC) GetLJBEOGOEJIJ() *CEIIKIIFBBB {
	if x != nil {
		return x.LJBEOGOEJIJ
	}
	return nil
}

var File_CLENLGMHIGC_proto protoreflect.FileDescriptor

var file_CLENLGMHIGC_proto_rawDesc = []byte{
	0x0a, 0x11, 0x43, 0x4c, 0x45, 0x4e, 0x4c, 0x47, 0x4d, 0x48, 0x49, 0x47, 0x43, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x4a, 0x4f, 0x43, 0x47, 0x50, 0x4e, 0x45, 0x4c, 0x4f, 0x42, 0x4b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x43, 0x45, 0x49, 0x49, 0x4b, 0x49, 0x49, 0x46,
	0x42, 0x42, 0x42, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x49, 0x48, 0x43, 0x4d, 0x50,
	0x49, 0x45, 0x4b, 0x4e, 0x46, 0x42, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdd, 0x01, 0x0a,
	0x0b, 0x43, 0x4c, 0x45, 0x4e, 0x4c, 0x47, 0x4d, 0x48, 0x49, 0x47, 0x43, 0x12, 0x19, 0x0a, 0x08,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x49, 0x4d, 0x46, 0x4e, 0x4b,
	0x4a, 0x4b, 0x43, 0x4d, 0x4d, 0x49, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x49, 0x4d,
	0x46, 0x4e, 0x4b, 0x4a, 0x4b, 0x43, 0x4d, 0x4d, 0x49, 0x12, 0x2f, 0x0a, 0x0b, 0x47, 0x4e, 0x43,
	0x4c, 0x4a, 0x41, 0x48, 0x48, 0x42, 0x4b, 0x4f, 0x18, 0xea, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x49, 0x48, 0x43, 0x4d, 0x50, 0x49, 0x45, 0x4b, 0x4e, 0x46, 0x42, 0x52, 0x0b, 0x47,
	0x4e, 0x43, 0x4c, 0x4a, 0x41, 0x48, 0x48, 0x42, 0x4b, 0x4f, 0x12, 0x2f, 0x0a, 0x0b, 0x43, 0x44,
	0x4b, 0x43, 0x4e, 0x4b, 0x4c, 0x50, 0x49, 0x47, 0x4a, 0x18, 0xec, 0x0c, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x4a, 0x4f, 0x43, 0x47, 0x50, 0x4e, 0x45, 0x4c, 0x4f, 0x42, 0x4b, 0x52, 0x0b,
	0x43, 0x44, 0x4b, 0x43, 0x4e, 0x4b, 0x4c, 0x50, 0x49, 0x47, 0x4a, 0x12, 0x2f, 0x0a, 0x0b, 0x4c,
	0x4a, 0x42, 0x45, 0x4f, 0x47, 0x4f, 0x45, 0x4a, 0x49, 0x4a, 0x18, 0xba, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x43, 0x45, 0x49, 0x49, 0x4b, 0x49, 0x49, 0x46, 0x42, 0x42, 0x42, 0x52,
	0x0b, 0x4c, 0x4a, 0x42, 0x45, 0x4f, 0x47, 0x4f, 0x45, 0x4a, 0x49, 0x4a, 0x42, 0x28, 0x5a, 0x08,
	0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x1b, 0x45, 0x67, 0x67, 0x4c, 0x69,
	0x6e, 0x6b, 0x2e, 0x44, 0x61, 0x6e, 0x68, 0x65, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_CLENLGMHIGC_proto_rawDescOnce sync.Once
	file_CLENLGMHIGC_proto_rawDescData = file_CLENLGMHIGC_proto_rawDesc
)

func file_CLENLGMHIGC_proto_rawDescGZIP() []byte {
	file_CLENLGMHIGC_proto_rawDescOnce.Do(func() {
		file_CLENLGMHIGC_proto_rawDescData = protoimpl.X.CompressGZIP(file_CLENLGMHIGC_proto_rawDescData)
	})
	return file_CLENLGMHIGC_proto_rawDescData
}

var file_CLENLGMHIGC_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CLENLGMHIGC_proto_goTypes = []interface{}{
	(*CLENLGMHIGC)(nil), // 0: CLENLGMHIGC
	(*IHCMPIEKNFB)(nil), // 1: IHCMPIEKNFB
	(*JOCGPNELOBK)(nil), // 2: JOCGPNELOBK
	(*CEIIKIIFBBB)(nil), // 3: CEIIKIIFBBB
}
var file_CLENLGMHIGC_proto_depIdxs = []int32{
	1, // 0: CLENLGMHIGC.GNCLJAHHBKO:type_name -> IHCMPIEKNFB
	2, // 1: CLENLGMHIGC.CDKCNKLPIGJ:type_name -> JOCGPNELOBK
	3, // 2: CLENLGMHIGC.LJBEOGOEJIJ:type_name -> CEIIKIIFBBB
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_CLENLGMHIGC_proto_init() }
func file_CLENLGMHIGC_proto_init() {
	if File_CLENLGMHIGC_proto != nil {
		return
	}
	file_JOCGPNELOBK_proto_init()
	file_CEIIKIIFBBB_proto_init()
	file_IHCMPIEKNFB_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_CLENLGMHIGC_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CLENLGMHIGC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CLENLGMHIGC_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CLENLGMHIGC_proto_goTypes,
		DependencyIndexes: file_CLENLGMHIGC_proto_depIdxs,
		MessageInfos:      file_CLENLGMHIGC_proto_msgTypes,
	}.Build()
	File_CLENLGMHIGC_proto = out.File
	file_CLENLGMHIGC_proto_rawDesc = nil
	file_CLENLGMHIGC_proto_goTypes = nil
	file_CLENLGMHIGC_proto_depIdxs = nil
}
