// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: COCKDENJGPM.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type COCKDENJGPM int32

const (
	COCKDENJGPM_ROGUE_BOOTH_NONE    COCKDENJGPM = 0
	COCKDENJGPM_ROGUE_BOOTH_EMPTY   COCKDENJGPM = 1
	COCKDENJGPM_ROGUE_BOOTH_DISPLAY COCKDENJGPM = 2
)

// Enum value maps for COCKDENJGPM.
var (
	COCKDENJGPM_name = map[int32]string{
		0: "ROGUE_BOOTH_NONE",
		1: "ROGUE_BOOTH_EMPTY",
		2: "ROGUE_BOOTH_DISPLAY",
	}
	COCKDENJGPM_value = map[string]int32{
		"ROGUE_BOOTH_NONE":    0,
		"ROGUE_BOOTH_EMPTY":   1,
		"ROGUE_BOOTH_DISPLAY": 2,
	}
)

func (x COCKDENJGPM) Enum() *COCKDENJGPM {
	p := new(COCKDENJGPM)
	*p = x
	return p
}

func (x COCKDENJGPM) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (COCKDENJGPM) Descriptor() protoreflect.EnumDescriptor {
	return file_COCKDENJGPM_proto_enumTypes[0].Descriptor()
}

func (COCKDENJGPM) Type() protoreflect.EnumType {
	return &file_COCKDENJGPM_proto_enumTypes[0]
}

func (x COCKDENJGPM) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use COCKDENJGPM.Descriptor instead.
func (COCKDENJGPM) EnumDescriptor() ([]byte, []int) {
	return file_COCKDENJGPM_proto_rawDescGZIP(), []int{0}
}

var File_COCKDENJGPM_proto protoreflect.FileDescriptor

var file_COCKDENJGPM_proto_rawDesc = []byte{
	0x0a, 0x11, 0x43, 0x4f, 0x43, 0x4b, 0x44, 0x45, 0x4e, 0x4a, 0x47, 0x50, 0x4d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2a, 0x53, 0x0a, 0x0b, 0x43, 0x4f, 0x43, 0x4b, 0x44, 0x45, 0x4e, 0x4a, 0x47,
	0x50, 0x4d, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x4f, 0x47, 0x55, 0x45, 0x5f, 0x42, 0x4f, 0x4f, 0x54,
	0x48, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x4f, 0x47, 0x55,
	0x45, 0x5f, 0x42, 0x4f, 0x4f, 0x54, 0x48, 0x5f, 0x45, 0x4d, 0x50, 0x54, 0x59, 0x10, 0x01, 0x12,
	0x17, 0x0a, 0x13, 0x52, 0x4f, 0x47, 0x55, 0x45, 0x5f, 0x42, 0x4f, 0x4f, 0x54, 0x48, 0x5f, 0x44,
	0x49, 0x53, 0x50, 0x4c, 0x41, 0x59, 0x10, 0x02, 0x42, 0x28, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x1b, 0x45, 0x67, 0x67, 0x4c, 0x69, 0x6e, 0x6b, 0x2e, 0x44,
	0x61, 0x6e, 0x68, 0x65, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_COCKDENJGPM_proto_rawDescOnce sync.Once
	file_COCKDENJGPM_proto_rawDescData = file_COCKDENJGPM_proto_rawDesc
)

func file_COCKDENJGPM_proto_rawDescGZIP() []byte {
	file_COCKDENJGPM_proto_rawDescOnce.Do(func() {
		file_COCKDENJGPM_proto_rawDescData = protoimpl.X.CompressGZIP(file_COCKDENJGPM_proto_rawDescData)
	})
	return file_COCKDENJGPM_proto_rawDescData
}

var file_COCKDENJGPM_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_COCKDENJGPM_proto_goTypes = []interface{}{
	(COCKDENJGPM)(0), // 0: COCKDENJGPM
}
var file_COCKDENJGPM_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_COCKDENJGPM_proto_init() }
func file_COCKDENJGPM_proto_init() {
	if File_COCKDENJGPM_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_COCKDENJGPM_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_COCKDENJGPM_proto_goTypes,
		DependencyIndexes: file_COCKDENJGPM_proto_depIdxs,
		EnumInfos:         file_COCKDENJGPM_proto_enumTypes,
	}.Build()
	File_COCKDENJGPM_proto = out.File
	file_COCKDENJGPM_proto_rawDesc = nil
	file_COCKDENJGPM_proto_goTypes = nil
	file_COCKDENJGPM_proto_depIdxs = nil
}
