// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: DKIBHFPOINL.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DKIBHFPOINL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvatarId    uint32 `protobuf:"varint,1,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`
	PBHHMLCDAHE int32  `protobuf:"varint,2,opt,name=PBHHMLCDAHE,proto3" json:"PBHHMLCDAHE,omitempty"`
}

func (x *DKIBHFPOINL) Reset() {
	*x = DKIBHFPOINL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_DKIBHFPOINL_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DKIBHFPOINL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DKIBHFPOINL) ProtoMessage() {}

func (x *DKIBHFPOINL) ProtoReflect() protoreflect.Message {
	mi := &file_DKIBHFPOINL_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DKIBHFPOINL.ProtoReflect.Descriptor instead.
func (*DKIBHFPOINL) Descriptor() ([]byte, []int) {
	return file_DKIBHFPOINL_proto_rawDescGZIP(), []int{0}
}

func (x *DKIBHFPOINL) GetAvatarId() uint32 {
	if x != nil {
		return x.AvatarId
	}
	return 0
}

func (x *DKIBHFPOINL) GetPBHHMLCDAHE() int32 {
	if x != nil {
		return x.PBHHMLCDAHE
	}
	return 0
}

var File_DKIBHFPOINL_proto protoreflect.FileDescriptor

var file_DKIBHFPOINL_proto_rawDesc = []byte{
	0x0a, 0x11, 0x44, 0x4b, 0x49, 0x42, 0x48, 0x46, 0x50, 0x4f, 0x49, 0x4e, 0x4c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x0b, 0x44, 0x4b, 0x49, 0x42, 0x48, 0x46, 0x50, 0x4f, 0x49,
	0x4e, 0x4c, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x50, 0x42, 0x48, 0x48, 0x4d, 0x4c, 0x43, 0x44, 0x41, 0x48, 0x45, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x50, 0x42, 0x48, 0x48, 0x4d, 0x4c, 0x43, 0x44, 0x41, 0x48,
	0x45, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_DKIBHFPOINL_proto_rawDescOnce sync.Once
	file_DKIBHFPOINL_proto_rawDescData = file_DKIBHFPOINL_proto_rawDesc
)

func file_DKIBHFPOINL_proto_rawDescGZIP() []byte {
	file_DKIBHFPOINL_proto_rawDescOnce.Do(func() {
		file_DKIBHFPOINL_proto_rawDescData = protoimpl.X.CompressGZIP(file_DKIBHFPOINL_proto_rawDescData)
	})
	return file_DKIBHFPOINL_proto_rawDescData
}

var file_DKIBHFPOINL_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_DKIBHFPOINL_proto_goTypes = []interface{}{
	(*DKIBHFPOINL)(nil), // 0: DKIBHFPOINL
}
var file_DKIBHFPOINL_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_DKIBHFPOINL_proto_init() }
func file_DKIBHFPOINL_proto_init() {
	if File_DKIBHFPOINL_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_DKIBHFPOINL_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DKIBHFPOINL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_DKIBHFPOINL_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_DKIBHFPOINL_proto_goTypes,
		DependencyIndexes: file_DKIBHFPOINL_proto_depIdxs,
		MessageInfos:      file_DKIBHFPOINL_proto_msgTypes,
	}.Build()
	File_DKIBHFPOINL_proto = out.File
	file_DKIBHFPOINL_proto_rawDesc = nil
	file_DKIBHFPOINL_proto_goTypes = nil
	file_DKIBHFPOINL_proto_depIdxs = nil
}
