// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: EHOELLPNCFK.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EHOELLPNCFK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AJBNGDFNHEP uint32   `protobuf:"varint,10,opt,name=AJBNGDFNHEP,proto3" json:"AJBNGDFNHEP,omitempty"`
	MAEMONLDCDL bool     `protobuf:"varint,9,opt,name=MAEMONLDCDL,proto3" json:"MAEMONLDCDL,omitempty"`
	NLGJKADDFDP []uint32 `protobuf:"varint,14,rep,packed,name=NLGJKADDFDP,proto3" json:"NLGJKADDFDP,omitempty"`
	EFFGFPDMHKN uint32   `protobuf:"varint,15,opt,name=EFFGFPDMHKN,proto3" json:"EFFGFPDMHKN,omitempty"`
	LAJIEODCOKG []uint32 `protobuf:"varint,5,rep,packed,name=LAJIEODCOKG,proto3" json:"LAJIEODCOKG,omitempty"`
	NIGNBLPPCOJ uint32   `protobuf:"varint,13,opt,name=NIGNBLPPCOJ,proto3" json:"NIGNBLPPCOJ,omitempty"`
}

func (x *EHOELLPNCFK) Reset() {
	*x = EHOELLPNCFK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_EHOELLPNCFK_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EHOELLPNCFK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EHOELLPNCFK) ProtoMessage() {}

func (x *EHOELLPNCFK) ProtoReflect() protoreflect.Message {
	mi := &file_EHOELLPNCFK_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EHOELLPNCFK.ProtoReflect.Descriptor instead.
func (*EHOELLPNCFK) Descriptor() ([]byte, []int) {
	return file_EHOELLPNCFK_proto_rawDescGZIP(), []int{0}
}

func (x *EHOELLPNCFK) GetAJBNGDFNHEP() uint32 {
	if x != nil {
		return x.AJBNGDFNHEP
	}
	return 0
}

func (x *EHOELLPNCFK) GetMAEMONLDCDL() bool {
	if x != nil {
		return x.MAEMONLDCDL
	}
	return false
}

func (x *EHOELLPNCFK) GetNLGJKADDFDP() []uint32 {
	if x != nil {
		return x.NLGJKADDFDP
	}
	return nil
}

func (x *EHOELLPNCFK) GetEFFGFPDMHKN() uint32 {
	if x != nil {
		return x.EFFGFPDMHKN
	}
	return 0
}

func (x *EHOELLPNCFK) GetLAJIEODCOKG() []uint32 {
	if x != nil {
		return x.LAJIEODCOKG
	}
	return nil
}

func (x *EHOELLPNCFK) GetNIGNBLPPCOJ() uint32 {
	if x != nil {
		return x.NIGNBLPPCOJ
	}
	return 0
}

var File_EHOELLPNCFK_proto protoreflect.FileDescriptor

var file_EHOELLPNCFK_proto_rawDesc = []byte{
	0x0a, 0x11, 0x45, 0x48, 0x4f, 0x45, 0x4c, 0x4c, 0x50, 0x4e, 0x43, 0x46, 0x4b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xd9, 0x01, 0x0a, 0x0b, 0x45, 0x48, 0x4f, 0x45, 0x4c, 0x4c, 0x50, 0x4e,
	0x43, 0x46, 0x4b, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x4a, 0x42, 0x4e, 0x47, 0x44, 0x46, 0x4e, 0x48,
	0x45, 0x50, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x41, 0x4a, 0x42, 0x4e, 0x47, 0x44,
	0x46, 0x4e, 0x48, 0x45, 0x50, 0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x41, 0x45, 0x4d, 0x4f, 0x4e, 0x4c,
	0x44, 0x43, 0x44, 0x4c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x4d, 0x41, 0x45, 0x4d,
	0x4f, 0x4e, 0x4c, 0x44, 0x43, 0x44, 0x4c, 0x12, 0x20, 0x0a, 0x0b, 0x4e, 0x4c, 0x47, 0x4a, 0x4b,
	0x41, 0x44, 0x44, 0x46, 0x44, 0x50, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0b, 0x4e, 0x4c,
	0x47, 0x4a, 0x4b, 0x41, 0x44, 0x44, 0x46, 0x44, 0x50, 0x12, 0x20, 0x0a, 0x0b, 0x45, 0x46, 0x46,
	0x47, 0x46, 0x50, 0x44, 0x4d, 0x48, 0x4b, 0x4e, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x45, 0x46, 0x46, 0x47, 0x46, 0x50, 0x44, 0x4d, 0x48, 0x4b, 0x4e, 0x12, 0x20, 0x0a, 0x0b, 0x4c,
	0x41, 0x4a, 0x49, 0x45, 0x4f, 0x44, 0x43, 0x4f, 0x4b, 0x47, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0d,
	0x52, 0x0b, 0x4c, 0x41, 0x4a, 0x49, 0x45, 0x4f, 0x44, 0x43, 0x4f, 0x4b, 0x47, 0x12, 0x20, 0x0a,
	0x0b, 0x4e, 0x49, 0x47, 0x4e, 0x42, 0x4c, 0x50, 0x50, 0x43, 0x4f, 0x4a, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0b, 0x4e, 0x49, 0x47, 0x4e, 0x42, 0x4c, 0x50, 0x50, 0x43, 0x4f, 0x4a, 0x42,
	0x28, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x1b, 0x45, 0x67,
	0x67, 0x4c, 0x69, 0x6e, 0x6b, 0x2e, 0x44, 0x61, 0x6e, 0x68, 0x65, 0x6e, 0x67, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_EHOELLPNCFK_proto_rawDescOnce sync.Once
	file_EHOELLPNCFK_proto_rawDescData = file_EHOELLPNCFK_proto_rawDesc
)

func file_EHOELLPNCFK_proto_rawDescGZIP() []byte {
	file_EHOELLPNCFK_proto_rawDescOnce.Do(func() {
		file_EHOELLPNCFK_proto_rawDescData = protoimpl.X.CompressGZIP(file_EHOELLPNCFK_proto_rawDescData)
	})
	return file_EHOELLPNCFK_proto_rawDescData
}

var file_EHOELLPNCFK_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_EHOELLPNCFK_proto_goTypes = []interface{}{
	(*EHOELLPNCFK)(nil), // 0: EHOELLPNCFK
}
var file_EHOELLPNCFK_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_EHOELLPNCFK_proto_init() }
func file_EHOELLPNCFK_proto_init() {
	if File_EHOELLPNCFK_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_EHOELLPNCFK_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EHOELLPNCFK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_EHOELLPNCFK_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_EHOELLPNCFK_proto_goTypes,
		DependencyIndexes: file_EHOELLPNCFK_proto_depIdxs,
		MessageInfos:      file_EHOELLPNCFK_proto_msgTypes,
	}.Build()
	File_EHOELLPNCFK_proto = out.File
	file_EHOELLPNCFK_proto_rawDesc = nil
	file_EHOELLPNCFK_proto_goTypes = nil
	file_EHOELLPNCFK_proto_depIdxs = nil
}
