// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: EKJOBFKOMIE.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EKJOBFKOMIE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EEPOKPJHHHB bool         `protobuf:"varint,14,opt,name=EEPOKPJHHHB,proto3" json:"EEPOKPJHHHB,omitempty"`
	BlackList   *GKBGBHMMIDP `protobuf:"bytes,10,opt,name=black_list,json=blackList,proto3" json:"black_list,omitempty"`
}

func (x *EKJOBFKOMIE) Reset() {
	*x = EKJOBFKOMIE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_EKJOBFKOMIE_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EKJOBFKOMIE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EKJOBFKOMIE) ProtoMessage() {}

func (x *EKJOBFKOMIE) ProtoReflect() protoreflect.Message {
	mi := &file_EKJOBFKOMIE_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EKJOBFKOMIE.ProtoReflect.Descriptor instead.
func (*EKJOBFKOMIE) Descriptor() ([]byte, []int) {
	return file_EKJOBFKOMIE_proto_rawDescGZIP(), []int{0}
}

func (x *EKJOBFKOMIE) GetEEPOKPJHHHB() bool {
	if x != nil {
		return x.EEPOKPJHHHB
	}
	return false
}

func (x *EKJOBFKOMIE) GetBlackList() *GKBGBHMMIDP {
	if x != nil {
		return x.BlackList
	}
	return nil
}

var File_EKJOBFKOMIE_proto protoreflect.FileDescriptor

var file_EKJOBFKOMIE_proto_rawDesc = []byte{
	0x0a, 0x11, 0x45, 0x4b, 0x4a, 0x4f, 0x42, 0x46, 0x4b, 0x4f, 0x4d, 0x49, 0x45, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x47, 0x4b, 0x42, 0x47, 0x42, 0x48, 0x4d, 0x4d, 0x49, 0x44, 0x50,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5c, 0x0a, 0x0b, 0x45, 0x4b, 0x4a, 0x4f, 0x42, 0x46,
	0x4b, 0x4f, 0x4d, 0x49, 0x45, 0x12, 0x20, 0x0a, 0x0b, 0x45, 0x45, 0x50, 0x4f, 0x4b, 0x50, 0x4a,
	0x48, 0x48, 0x48, 0x42, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x45, 0x45, 0x50, 0x4f,
	0x4b, 0x50, 0x4a, 0x48, 0x48, 0x48, 0x42, 0x12, 0x2b, 0x0a, 0x0a, 0x62, 0x6c, 0x61, 0x63, 0x6b,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x47, 0x4b,
	0x42, 0x47, 0x42, 0x48, 0x4d, 0x4d, 0x49, 0x44, 0x50, 0x52, 0x09, 0x62, 0x6c, 0x61, 0x63, 0x6b,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x2e, 0x5a, 0x0e, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x1b, 0x45, 0x67, 0x67, 0x4c, 0x69, 0x6e, 0x6b,
	0x2e, 0x44, 0x61, 0x6e, 0x68, 0x65, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_EKJOBFKOMIE_proto_rawDescOnce sync.Once
	file_EKJOBFKOMIE_proto_rawDescData = file_EKJOBFKOMIE_proto_rawDesc
)

func file_EKJOBFKOMIE_proto_rawDescGZIP() []byte {
	file_EKJOBFKOMIE_proto_rawDescOnce.Do(func() {
		file_EKJOBFKOMIE_proto_rawDescData = protoimpl.X.CompressGZIP(file_EKJOBFKOMIE_proto_rawDescData)
	})
	return file_EKJOBFKOMIE_proto_rawDescData
}

var file_EKJOBFKOMIE_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_EKJOBFKOMIE_proto_goTypes = []interface{}{
	(*EKJOBFKOMIE)(nil), // 0: EKJOBFKOMIE
	(*GKBGBHMMIDP)(nil), // 1: GKBGBHMMIDP
}
var file_EKJOBFKOMIE_proto_depIdxs = []int32{
	1, // 0: EKJOBFKOMIE.black_list:type_name -> GKBGBHMMIDP
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_EKJOBFKOMIE_proto_init() }
func file_EKJOBFKOMIE_proto_init() {
	if File_EKJOBFKOMIE_proto != nil {
		return
	}
	file_GKBGBHMMIDP_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_EKJOBFKOMIE_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EKJOBFKOMIE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_EKJOBFKOMIE_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_EKJOBFKOMIE_proto_goTypes,
		DependencyIndexes: file_EKJOBFKOMIE_proto_depIdxs,
		MessageInfos:      file_EKJOBFKOMIE_proto_msgTypes,
	}.Build()
	File_EKJOBFKOMIE_proto = out.File
	file_EKJOBFKOMIE_proto_rawDesc = nil
	file_EKJOBFKOMIE_proto_goTypes = nil
	file_EKJOBFKOMIE_proto_depIdxs = nil
}
