// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: GetChallengeGroupStatisticsScRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetChallengeGroupStatisticsScRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode uint32 `protobuf:"varint,4,opt,name=retcode,proto3" json:"retcode,omitempty"`
	GroupId uint32 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// Types that are assignable to NMALKAEHGCK:
	//
	//	*GetChallengeGroupStatisticsScRsp_ADMPDKACMMP
	//	*GetChallengeGroupStatisticsScRsp_JCEOOEGJKNE
	//	*GetChallengeGroupStatisticsScRsp_LBKCIKIDLCG
	NMALKAEHGCK isGetChallengeGroupStatisticsScRsp_NMALKAEHGCK `protobuf_oneof:"NMALKAEHGCK"`
}

func (x *GetChallengeGroupStatisticsScRsp) Reset() {
	*x = GetChallengeGroupStatisticsScRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetChallengeGroupStatisticsScRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChallengeGroupStatisticsScRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChallengeGroupStatisticsScRsp) ProtoMessage() {}

func (x *GetChallengeGroupStatisticsScRsp) ProtoReflect() protoreflect.Message {
	mi := &file_GetChallengeGroupStatisticsScRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChallengeGroupStatisticsScRsp.ProtoReflect.Descriptor instead.
func (*GetChallengeGroupStatisticsScRsp) Descriptor() ([]byte, []int) {
	return file_GetChallengeGroupStatisticsScRsp_proto_rawDescGZIP(), []int{0}
}

func (x *GetChallengeGroupStatisticsScRsp) GetRetcode() uint32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *GetChallengeGroupStatisticsScRsp) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (m *GetChallengeGroupStatisticsScRsp) GetNMALKAEHGCK() isGetChallengeGroupStatisticsScRsp_NMALKAEHGCK {
	if m != nil {
		return m.NMALKAEHGCK
	}
	return nil
}

func (x *GetChallengeGroupStatisticsScRsp) GetADMPDKACMMP() *FPJBPNBCBAL {
	if x, ok := x.GetNMALKAEHGCK().(*GetChallengeGroupStatisticsScRsp_ADMPDKACMMP); ok {
		return x.ADMPDKACMMP
	}
	return nil
}

func (x *GetChallengeGroupStatisticsScRsp) GetJCEOOEGJKNE() *MJAPECHBENG {
	if x, ok := x.GetNMALKAEHGCK().(*GetChallengeGroupStatisticsScRsp_JCEOOEGJKNE); ok {
		return x.JCEOOEGJKNE
	}
	return nil
}

func (x *GetChallengeGroupStatisticsScRsp) GetLBKCIKIDLCG() *EFBDHLEJDJM {
	if x, ok := x.GetNMALKAEHGCK().(*GetChallengeGroupStatisticsScRsp_LBKCIKIDLCG); ok {
		return x.LBKCIKIDLCG
	}
	return nil
}

type isGetChallengeGroupStatisticsScRsp_NMALKAEHGCK interface {
	isGetChallengeGroupStatisticsScRsp_NMALKAEHGCK()
}

type GetChallengeGroupStatisticsScRsp_ADMPDKACMMP struct {
	ADMPDKACMMP *FPJBPNBCBAL `protobuf:"bytes,3,opt,name=ADMPDKACMMP,proto3,oneof"`
}

type GetChallengeGroupStatisticsScRsp_JCEOOEGJKNE struct {
	JCEOOEGJKNE *MJAPECHBENG `protobuf:"bytes,9,opt,name=JCEOOEGJKNE,proto3,oneof"`
}

type GetChallengeGroupStatisticsScRsp_LBKCIKIDLCG struct {
	LBKCIKIDLCG *EFBDHLEJDJM `protobuf:"bytes,14,opt,name=LBKCIKIDLCG,proto3,oneof"`
}

func (*GetChallengeGroupStatisticsScRsp_ADMPDKACMMP) isGetChallengeGroupStatisticsScRsp_NMALKAEHGCK() {
}

func (*GetChallengeGroupStatisticsScRsp_JCEOOEGJKNE) isGetChallengeGroupStatisticsScRsp_NMALKAEHGCK() {
}

func (*GetChallengeGroupStatisticsScRsp_LBKCIKIDLCG) isGetChallengeGroupStatisticsScRsp_NMALKAEHGCK() {
}

var File_GetChallengeGroupStatisticsScRsp_proto protoreflect.FileDescriptor

var file_GetChallengeGroupStatisticsScRsp_proto_rawDesc = []byte{
	0x0a, 0x26, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x53, 0x63, 0x52,
	0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x45, 0x46, 0x42, 0x44, 0x48, 0x4c,
	0x45, 0x4a, 0x44, 0x4a, 0x4d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x4d, 0x4a, 0x41,
	0x50, 0x45, 0x43, 0x48, 0x42, 0x45, 0x4e, 0x47, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11,
	0x46, 0x50, 0x4a, 0x42, 0x50, 0x4e, 0x42, 0x43, 0x42, 0x41, 0x4c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xfc, 0x01, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e,
	0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x73, 0x53, 0x63, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x0b, 0x41,
	0x44, 0x4d, 0x50, 0x44, 0x4b, 0x41, 0x43, 0x4d, 0x4d, 0x50, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x46, 0x50, 0x4a, 0x42, 0x50, 0x4e, 0x42, 0x43, 0x42, 0x41, 0x4c, 0x48, 0x00,
	0x52, 0x0b, 0x41, 0x44, 0x4d, 0x50, 0x44, 0x4b, 0x41, 0x43, 0x4d, 0x4d, 0x50, 0x12, 0x30, 0x0a,
	0x0b, 0x4a, 0x43, 0x45, 0x4f, 0x4f, 0x45, 0x47, 0x4a, 0x4b, 0x4e, 0x45, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4d, 0x4a, 0x41, 0x50, 0x45, 0x43, 0x48, 0x42, 0x45, 0x4e, 0x47,
	0x48, 0x00, 0x52, 0x0b, 0x4a, 0x43, 0x45, 0x4f, 0x4f, 0x45, 0x47, 0x4a, 0x4b, 0x4e, 0x45, 0x12,
	0x30, 0x0a, 0x0b, 0x4c, 0x42, 0x4b, 0x43, 0x49, 0x4b, 0x49, 0x44, 0x4c, 0x43, 0x47, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x45, 0x46, 0x42, 0x44, 0x48, 0x4c, 0x45, 0x4a, 0x44,
	0x4a, 0x4d, 0x48, 0x00, 0x52, 0x0b, 0x4c, 0x42, 0x4b, 0x43, 0x49, 0x4b, 0x49, 0x44, 0x4c, 0x43,
	0x47, 0x42, 0x0d, 0x0a, 0x0b, 0x4e, 0x4d, 0x41, 0x4c, 0x4b, 0x41, 0x45, 0x48, 0x47, 0x43, 0x4b,
	0x42, 0x2e, 0x5a, 0x0e, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0xaa, 0x02, 0x1b, 0x45, 0x67, 0x67, 0x4c, 0x69, 0x6e, 0x6b, 0x2e, 0x44, 0x61, 0x6e,
	0x68, 0x65, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_GetChallengeGroupStatisticsScRsp_proto_rawDescOnce sync.Once
	file_GetChallengeGroupStatisticsScRsp_proto_rawDescData = file_GetChallengeGroupStatisticsScRsp_proto_rawDesc
)

func file_GetChallengeGroupStatisticsScRsp_proto_rawDescGZIP() []byte {
	file_GetChallengeGroupStatisticsScRsp_proto_rawDescOnce.Do(func() {
		file_GetChallengeGroupStatisticsScRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_GetChallengeGroupStatisticsScRsp_proto_rawDescData)
	})
	return file_GetChallengeGroupStatisticsScRsp_proto_rawDescData
}

var file_GetChallengeGroupStatisticsScRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_GetChallengeGroupStatisticsScRsp_proto_goTypes = []interface{}{
	(*GetChallengeGroupStatisticsScRsp)(nil), // 0: GetChallengeGroupStatisticsScRsp
	(*FPJBPNBCBAL)(nil),                      // 1: FPJBPNBCBAL
	(*MJAPECHBENG)(nil),                      // 2: MJAPECHBENG
	(*EFBDHLEJDJM)(nil),                      // 3: EFBDHLEJDJM
}
var file_GetChallengeGroupStatisticsScRsp_proto_depIdxs = []int32{
	1, // 0: GetChallengeGroupStatisticsScRsp.ADMPDKACMMP:type_name -> FPJBPNBCBAL
	2, // 1: GetChallengeGroupStatisticsScRsp.JCEOOEGJKNE:type_name -> MJAPECHBENG
	3, // 2: GetChallengeGroupStatisticsScRsp.LBKCIKIDLCG:type_name -> EFBDHLEJDJM
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_GetChallengeGroupStatisticsScRsp_proto_init() }
func file_GetChallengeGroupStatisticsScRsp_proto_init() {
	if File_GetChallengeGroupStatisticsScRsp_proto != nil {
		return
	}
	file_EFBDHLEJDJM_proto_init()
	file_MJAPECHBENG_proto_init()
	file_FPJBPNBCBAL_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_GetChallengeGroupStatisticsScRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChallengeGroupStatisticsScRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_GetChallengeGroupStatisticsScRsp_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*GetChallengeGroupStatisticsScRsp_ADMPDKACMMP)(nil),
		(*GetChallengeGroupStatisticsScRsp_JCEOOEGJKNE)(nil),
		(*GetChallengeGroupStatisticsScRsp_LBKCIKIDLCG)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GetChallengeGroupStatisticsScRsp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetChallengeGroupStatisticsScRsp_proto_goTypes,
		DependencyIndexes: file_GetChallengeGroupStatisticsScRsp_proto_depIdxs,
		MessageInfos:      file_GetChallengeGroupStatisticsScRsp_proto_msgTypes,
	}.Build()
	File_GetChallengeGroupStatisticsScRsp_proto = out.File
	file_GetChallengeGroupStatisticsScRsp_proto_rawDesc = nil
	file_GetChallengeGroupStatisticsScRsp_proto_goTypes = nil
	file_GetChallengeGroupStatisticsScRsp_proto_depIdxs = nil
}
