// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: GetPlayerReturnMultiDropInfoCsReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPlayerReturnMultiDropInfoCsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPlayerReturnMultiDropInfoCsReq) Reset() {
	*x = GetPlayerReturnMultiDropInfoCsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetPlayerReturnMultiDropInfoCsReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlayerReturnMultiDropInfoCsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerReturnMultiDropInfoCsReq) ProtoMessage() {}

func (x *GetPlayerReturnMultiDropInfoCsReq) ProtoReflect() protoreflect.Message {
	mi := &file_GetPlayerReturnMultiDropInfoCsReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerReturnMultiDropInfoCsReq.ProtoReflect.Descriptor instead.
func (*GetPlayerReturnMultiDropInfoCsReq) Descriptor() ([]byte, []int) {
	return file_GetPlayerReturnMultiDropInfoCsReq_proto_rawDescGZIP(), []int{0}
}

var File_GetPlayerReturnMultiDropInfoCsReq_proto protoreflect.FileDescriptor

var file_GetPlayerReturnMultiDropInfoCsReq_proto_rawDesc = []byte{
	0x0a, 0x27, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x44, 0x72, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x73,
	0x52, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x21, 0x47, 0x65, 0x74,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x4d, 0x75, 0x6c, 0x74,
	0x69, 0x44, 0x72, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x73, 0x52, 0x65, 0x71, 0x42, 0x2e,
	0x5a, 0x0e, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0xaa, 0x02, 0x1b, 0x45, 0x67, 0x67, 0x4c, 0x69, 0x6e, 0x6b, 0x2e, 0x44, 0x61, 0x6e, 0x68, 0x65,
	0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_GetPlayerReturnMultiDropInfoCsReq_proto_rawDescOnce sync.Once
	file_GetPlayerReturnMultiDropInfoCsReq_proto_rawDescData = file_GetPlayerReturnMultiDropInfoCsReq_proto_rawDesc
)

func file_GetPlayerReturnMultiDropInfoCsReq_proto_rawDescGZIP() []byte {
	file_GetPlayerReturnMultiDropInfoCsReq_proto_rawDescOnce.Do(func() {
		file_GetPlayerReturnMultiDropInfoCsReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_GetPlayerReturnMultiDropInfoCsReq_proto_rawDescData)
	})
	return file_GetPlayerReturnMultiDropInfoCsReq_proto_rawDescData
}

var file_GetPlayerReturnMultiDropInfoCsReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_GetPlayerReturnMultiDropInfoCsReq_proto_goTypes = []interface{}{
	(*GetPlayerReturnMultiDropInfoCsReq)(nil), // 0: GetPlayerReturnMultiDropInfoCsReq
}
var file_GetPlayerReturnMultiDropInfoCsReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_GetPlayerReturnMultiDropInfoCsReq_proto_init() }
func file_GetPlayerReturnMultiDropInfoCsReq_proto_init() {
	if File_GetPlayerReturnMultiDropInfoCsReq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_GetPlayerReturnMultiDropInfoCsReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlayerReturnMultiDropInfoCsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GetPlayerReturnMultiDropInfoCsReq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetPlayerReturnMultiDropInfoCsReq_proto_goTypes,
		DependencyIndexes: file_GetPlayerReturnMultiDropInfoCsReq_proto_depIdxs,
		MessageInfos:      file_GetPlayerReturnMultiDropInfoCsReq_proto_msgTypes,
	}.Build()
	File_GetPlayerReturnMultiDropInfoCsReq_proto = out.File
	file_GetPlayerReturnMultiDropInfoCsReq_proto_rawDesc = nil
	file_GetPlayerReturnMultiDropInfoCsReq_proto_goTypes = nil
	file_GetPlayerReturnMultiDropInfoCsReq_proto_depIdxs = nil
}
