// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: IFNOEFNECDB.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IFNOEFNECDB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EMMPCOIHPDA int32         `protobuf:"varint,6,opt,name=EMMPCOIHPDA,proto3" json:"EMMPCOIHPDA,omitempty"`
	PFFEBADMFJN uint32        `protobuf:"varint,13,opt,name=PFFEBADMFJN,proto3" json:"PFFEBADMFJN,omitempty"`
	PJLOKNDIEGG bool          `protobuf:"varint,4,opt,name=PJLOKNDIEGG,proto3" json:"PJLOKNDIEGG,omitempty"`
	KCNJMAJBHPI uint32        `protobuf:"varint,2,opt,name=KCNJMAJBHPI,proto3" json:"KCNJMAJBHPI,omitempty"`
	CostData    *ItemCostData `protobuf:"bytes,1,opt,name=cost_data,json=costData,proto3" json:"cost_data,omitempty"`
}

func (x *IFNOEFNECDB) Reset() {
	*x = IFNOEFNECDB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_IFNOEFNECDB_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IFNOEFNECDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IFNOEFNECDB) ProtoMessage() {}

func (x *IFNOEFNECDB) ProtoReflect() protoreflect.Message {
	mi := &file_IFNOEFNECDB_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IFNOEFNECDB.ProtoReflect.Descriptor instead.
func (*IFNOEFNECDB) Descriptor() ([]byte, []int) {
	return file_IFNOEFNECDB_proto_rawDescGZIP(), []int{0}
}

func (x *IFNOEFNECDB) GetEMMPCOIHPDA() int32 {
	if x != nil {
		return x.EMMPCOIHPDA
	}
	return 0
}

func (x *IFNOEFNECDB) GetPFFEBADMFJN() uint32 {
	if x != nil {
		return x.PFFEBADMFJN
	}
	return 0
}

func (x *IFNOEFNECDB) GetPJLOKNDIEGG() bool {
	if x != nil {
		return x.PJLOKNDIEGG
	}
	return false
}

func (x *IFNOEFNECDB) GetKCNJMAJBHPI() uint32 {
	if x != nil {
		return x.KCNJMAJBHPI
	}
	return 0
}

func (x *IFNOEFNECDB) GetCostData() *ItemCostData {
	if x != nil {
		return x.CostData
	}
	return nil
}

var File_IFNOEFNECDB_proto protoreflect.FileDescriptor

var file_IFNOEFNECDB_proto_rawDesc = []byte{
	0x0a, 0x11, 0x49, 0x46, 0x4e, 0x4f, 0x45, 0x46, 0x4e, 0x45, 0x43, 0x44, 0x42, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x73, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc1, 0x01, 0x0a, 0x0b, 0x49, 0x46, 0x4e, 0x4f,
	0x45, 0x46, 0x4e, 0x45, 0x43, 0x44, 0x42, 0x12, 0x20, 0x0a, 0x0b, 0x45, 0x4d, 0x4d, 0x50, 0x43,
	0x4f, 0x49, 0x48, 0x50, 0x44, 0x41, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x45, 0x4d,
	0x4d, 0x50, 0x43, 0x4f, 0x49, 0x48, 0x50, 0x44, 0x41, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x46, 0x46,
	0x45, 0x42, 0x41, 0x44, 0x4d, 0x46, 0x4a, 0x4e, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x50, 0x46, 0x46, 0x45, 0x42, 0x41, 0x44, 0x4d, 0x46, 0x4a, 0x4e, 0x12, 0x20, 0x0a, 0x0b, 0x50,
	0x4a, 0x4c, 0x4f, 0x4b, 0x4e, 0x44, 0x49, 0x45, 0x47, 0x47, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0b, 0x50, 0x4a, 0x4c, 0x4f, 0x4b, 0x4e, 0x44, 0x49, 0x45, 0x47, 0x47, 0x12, 0x20, 0x0a,
	0x0b, 0x4b, 0x43, 0x4e, 0x4a, 0x4d, 0x41, 0x4a, 0x42, 0x48, 0x50, 0x49, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0b, 0x4b, 0x43, 0x4e, 0x4a, 0x4d, 0x41, 0x4a, 0x42, 0x48, 0x50, 0x49, 0x12,
	0x2a, 0x0a, 0x09, 0x63, 0x6f, 0x73, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x73, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x08, 0x63, 0x6f, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x42, 0x28, 0x5a, 0x08, 0x2e,
	0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x1b, 0x45, 0x67, 0x67, 0x4c, 0x69, 0x6e,
	0x6b, 0x2e, 0x44, 0x61, 0x6e, 0x68, 0x65, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_IFNOEFNECDB_proto_rawDescOnce sync.Once
	file_IFNOEFNECDB_proto_rawDescData = file_IFNOEFNECDB_proto_rawDesc
)

func file_IFNOEFNECDB_proto_rawDescGZIP() []byte {
	file_IFNOEFNECDB_proto_rawDescOnce.Do(func() {
		file_IFNOEFNECDB_proto_rawDescData = protoimpl.X.CompressGZIP(file_IFNOEFNECDB_proto_rawDescData)
	})
	return file_IFNOEFNECDB_proto_rawDescData
}

var file_IFNOEFNECDB_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_IFNOEFNECDB_proto_goTypes = []interface{}{
	(*IFNOEFNECDB)(nil),  // 0: IFNOEFNECDB
	(*ItemCostData)(nil), // 1: ItemCostData
}
var file_IFNOEFNECDB_proto_depIdxs = []int32{
	1, // 0: IFNOEFNECDB.cost_data:type_name -> ItemCostData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_IFNOEFNECDB_proto_init() }
func file_IFNOEFNECDB_proto_init() {
	if File_IFNOEFNECDB_proto != nil {
		return
	}
	file_ItemCostData_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_IFNOEFNECDB_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IFNOEFNECDB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_IFNOEFNECDB_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_IFNOEFNECDB_proto_goTypes,
		DependencyIndexes: file_IFNOEFNECDB_proto_depIdxs,
		MessageInfos:      file_IFNOEFNECDB_proto_msgTypes,
	}.Build()
	File_IFNOEFNECDB_proto = out.File
	file_IFNOEFNECDB_proto_rawDesc = nil
	file_IFNOEFNECDB_proto_goTypes = nil
	file_IFNOEFNECDB_proto_depIdxs = nil
}
