// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: KMGGNJAKPGI.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KMGGNJAKPGI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type         MissionSyncRecord `protobuf:"varint,8,opt,name=type,proto3,enum=MissionSyncRecord" json:"type,omitempty"`
	DisplayValue uint32            `protobuf:"varint,2,opt,name=display_value,json=displayValue,proto3" json:"display_value,omitempty"`
	Id           uint32            `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *KMGGNJAKPGI) Reset() {
	*x = KMGGNJAKPGI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KMGGNJAKPGI_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KMGGNJAKPGI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KMGGNJAKPGI) ProtoMessage() {}

func (x *KMGGNJAKPGI) ProtoReflect() protoreflect.Message {
	mi := &file_KMGGNJAKPGI_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KMGGNJAKPGI.ProtoReflect.Descriptor instead.
func (*KMGGNJAKPGI) Descriptor() ([]byte, []int) {
	return file_KMGGNJAKPGI_proto_rawDescGZIP(), []int{0}
}

func (x *KMGGNJAKPGI) GetType() MissionSyncRecord {
	if x != nil {
		return x.Type
	}
	return MissionSyncRecord_MISSION_SYNC_RECORD_NONE
}

func (x *KMGGNJAKPGI) GetDisplayValue() uint32 {
	if x != nil {
		return x.DisplayValue
	}
	return 0
}

func (x *KMGGNJAKPGI) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_KMGGNJAKPGI_proto protoreflect.FileDescriptor

var file_KMGGNJAKPGI_proto_rawDesc = []byte{
	0x0a, 0x11, 0x4b, 0x4d, 0x47, 0x47, 0x4e, 0x4a, 0x41, 0x4b, 0x50, 0x47, 0x49, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x79, 0x6e, 0x63,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6a, 0x0a, 0x0b,
	0x4b, 0x4d, 0x47, 0x47, 0x4e, 0x4a, 0x41, 0x4b, 0x50, 0x47, 0x49, 0x12, 0x26, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x4d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x64, 0x69, 0x73, 0x70,
	0x6c, 0x61, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x42, 0x2e, 0x5a, 0x0e, 0x2e, 0x2e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x1b, 0x45, 0x67, 0x67,
	0x4c, 0x69, 0x6e, 0x6b, 0x2e, 0x44, 0x61, 0x6e, 0x68, 0x65, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_KMGGNJAKPGI_proto_rawDescOnce sync.Once
	file_KMGGNJAKPGI_proto_rawDescData = file_KMGGNJAKPGI_proto_rawDesc
)

func file_KMGGNJAKPGI_proto_rawDescGZIP() []byte {
	file_KMGGNJAKPGI_proto_rawDescOnce.Do(func() {
		file_KMGGNJAKPGI_proto_rawDescData = protoimpl.X.CompressGZIP(file_KMGGNJAKPGI_proto_rawDescData)
	})
	return file_KMGGNJAKPGI_proto_rawDescData
}

var file_KMGGNJAKPGI_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_KMGGNJAKPGI_proto_goTypes = []interface{}{
	(*KMGGNJAKPGI)(nil),    // 0: KMGGNJAKPGI
	(MissionSyncRecord)(0), // 1: MissionSyncRecord
}
var file_KMGGNJAKPGI_proto_depIdxs = []int32{
	1, // 0: KMGGNJAKPGI.type:type_name -> MissionSyncRecord
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_KMGGNJAKPGI_proto_init() }
func file_KMGGNJAKPGI_proto_init() {
	if File_KMGGNJAKPGI_proto != nil {
		return
	}
	file_MissionSyncRecord_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_KMGGNJAKPGI_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KMGGNJAKPGI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_KMGGNJAKPGI_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_KMGGNJAKPGI_proto_goTypes,
		DependencyIndexes: file_KMGGNJAKPGI_proto_depIdxs,
		MessageInfos:      file_KMGGNJAKPGI_proto_msgTypes,
	}.Build()
	File_KMGGNJAKPGI_proto = out.File
	file_KMGGNJAKPGI_proto_rawDesc = nil
	file_KMGGNJAKPGI_proto_goTypes = nil
	file_KMGGNJAKPGI_proto_depIdxs = nil
}
