// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: MFMHHAMODGN.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MFMHHAMODGN int32

const (
	MFMHHAMODGN_CHESS_ROGUE_UPDATE_LEVEL_STATUS_BY_NONE   MFMHHAMODGN = 0
	MFMHHAMODGN_CHESS_ROGUE_UPDATE_LEVEL_STATUS_BY_DIALOG MFMHHAMODGN = 1
)

// Enum value maps for MFMHHAMODGN.
var (
	MFMHHAMODGN_name = map[int32]string{
		0: "CHESS_ROGUE_UPDATE_LEVEL_STATUS_BY_NONE",
		1: "CHESS_ROGUE_UPDATE_LEVEL_STATUS_BY_DIALOG",
	}
	MFMHHAMODGN_value = map[string]int32{
		"CHESS_ROGUE_UPDATE_LEVEL_STATUS_BY_NONE":   0,
		"CHESS_ROGUE_UPDATE_LEVEL_STATUS_BY_DIALOG": 1,
	}
)

func (x MFMHHAMODGN) Enum() *MFMHHAMODGN {
	p := new(MFMHHAMODGN)
	*p = x
	return p
}

func (x MFMHHAMODGN) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MFMHHAMODGN) Descriptor() protoreflect.EnumDescriptor {
	return file_MFMHHAMODGN_proto_enumTypes[0].Descriptor()
}

func (MFMHHAMODGN) Type() protoreflect.EnumType {
	return &file_MFMHHAMODGN_proto_enumTypes[0]
}

func (x MFMHHAMODGN) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MFMHHAMODGN.Descriptor instead.
func (MFMHHAMODGN) EnumDescriptor() ([]byte, []int) {
	return file_MFMHHAMODGN_proto_rawDescGZIP(), []int{0}
}

var File_MFMHHAMODGN_proto protoreflect.FileDescriptor

var file_MFMHHAMODGN_proto_rawDesc = []byte{
	0x0a, 0x11, 0x4d, 0x46, 0x4d, 0x48, 0x48, 0x41, 0x4d, 0x4f, 0x44, 0x47, 0x4e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2a, 0x69, 0x0a, 0x0b, 0x4d, 0x46, 0x4d, 0x48, 0x48, 0x41, 0x4d, 0x4f, 0x44,
	0x47, 0x4e, 0x12, 0x2b, 0x0a, 0x27, 0x43, 0x48, 0x45, 0x53, 0x53, 0x5f, 0x52, 0x4f, 0x47, 0x55,
	0x45, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x42, 0x59, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12,
	0x2d, 0x0a, 0x29, 0x43, 0x48, 0x45, 0x53, 0x53, 0x5f, 0x52, 0x4f, 0x47, 0x55, 0x45, 0x5f, 0x55,
	0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x42, 0x59, 0x5f, 0x44, 0x49, 0x41, 0x4c, 0x4f, 0x47, 0x10, 0x01, 0x42, 0x28,
	0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x1b, 0x45, 0x67, 0x67,
	0x4c, 0x69, 0x6e, 0x6b, 0x2e, 0x44, 0x61, 0x6e, 0x68, 0x65, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_MFMHHAMODGN_proto_rawDescOnce sync.Once
	file_MFMHHAMODGN_proto_rawDescData = file_MFMHHAMODGN_proto_rawDesc
)

func file_MFMHHAMODGN_proto_rawDescGZIP() []byte {
	file_MFMHHAMODGN_proto_rawDescOnce.Do(func() {
		file_MFMHHAMODGN_proto_rawDescData = protoimpl.X.CompressGZIP(file_MFMHHAMODGN_proto_rawDescData)
	})
	return file_MFMHHAMODGN_proto_rawDescData
}

var file_MFMHHAMODGN_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_MFMHHAMODGN_proto_goTypes = []interface{}{
	(MFMHHAMODGN)(0), // 0: MFMHHAMODGN
}
var file_MFMHHAMODGN_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_MFMHHAMODGN_proto_init() }
func file_MFMHHAMODGN_proto_init() {
	if File_MFMHHAMODGN_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MFMHHAMODGN_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MFMHHAMODGN_proto_goTypes,
		DependencyIndexes: file_MFMHHAMODGN_proto_depIdxs,
		EnumInfos:         file_MFMHHAMODGN_proto_enumTypes,
	}.Build()
	File_MFMHHAMODGN_proto = out.File
	file_MFMHHAMODGN_proto_rawDesc = nil
	file_MFMHHAMODGN_proto_goTypes = nil
	file_MFMHHAMODGN_proto_depIdxs = nil
}
