// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: OAKOJBOEMAA.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OAKOJBOEMAA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PBPDGAMKBPM *Vector      `protobuf:"bytes,11,opt,name=PBPDGAMKBPM,proto3" json:"PBPDGAMKBPM,omitempty"`
	MJINOEJMBON *GPDFECLFNHM `protobuf:"bytes,13,opt,name=MJINOEJMBON,proto3" json:"MJINOEJMBON,omitempty"`
}

func (x *OAKOJBOEMAA) Reset() {
	*x = OAKOJBOEMAA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OAKOJBOEMAA_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OAKOJBOEMAA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAKOJBOEMAA) ProtoMessage() {}

func (x *OAKOJBOEMAA) ProtoReflect() protoreflect.Message {
	mi := &file_OAKOJBOEMAA_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAKOJBOEMAA.ProtoReflect.Descriptor instead.
func (*OAKOJBOEMAA) Descriptor() ([]byte, []int) {
	return file_OAKOJBOEMAA_proto_rawDescGZIP(), []int{0}
}

func (x *OAKOJBOEMAA) GetPBPDGAMKBPM() *Vector {
	if x != nil {
		return x.PBPDGAMKBPM
	}
	return nil
}

func (x *OAKOJBOEMAA) GetMJINOEJMBON() *GPDFECLFNHM {
	if x != nil {
		return x.MJINOEJMBON
	}
	return nil
}

var File_OAKOJBOEMAA_proto protoreflect.FileDescriptor

var file_OAKOJBOEMAA_proto_rawDesc = []byte{
	0x0a, 0x11, 0x4f, 0x41, 0x4b, 0x4f, 0x4a, 0x42, 0x4f, 0x45, 0x4d, 0x41, 0x41, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x47, 0x50, 0x44, 0x46, 0x45, 0x43, 0x4c, 0x46, 0x4e, 0x48, 0x4d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68, 0x0a, 0x0b, 0x4f, 0x41, 0x4b, 0x4f, 0x4a, 0x42, 0x4f, 0x45,
	0x4d, 0x41, 0x41, 0x12, 0x29, 0x0a, 0x0b, 0x50, 0x42, 0x50, 0x44, 0x47, 0x41, 0x4d, 0x4b, 0x42,
	0x50, 0x4d, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x52, 0x0b, 0x50, 0x42, 0x50, 0x44, 0x47, 0x41, 0x4d, 0x4b, 0x42, 0x50, 0x4d, 0x12, 0x2e,
	0x0a, 0x0b, 0x4d, 0x4a, 0x49, 0x4e, 0x4f, 0x45, 0x4a, 0x4d, 0x42, 0x4f, 0x4e, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x47, 0x50, 0x44, 0x46, 0x45, 0x43, 0x4c, 0x46, 0x4e, 0x48,
	0x4d, 0x52, 0x0b, 0x4d, 0x4a, 0x49, 0x4e, 0x4f, 0x45, 0x4a, 0x4d, 0x42, 0x4f, 0x4e, 0x42, 0x2e,
	0x5a, 0x0e, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0xaa, 0x02, 0x1b, 0x45, 0x67, 0x67, 0x4c, 0x69, 0x6e, 0x6b, 0x2e, 0x44, 0x61, 0x6e, 0x68, 0x65,
	0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_OAKOJBOEMAA_proto_rawDescOnce sync.Once
	file_OAKOJBOEMAA_proto_rawDescData = file_OAKOJBOEMAA_proto_rawDesc
)

func file_OAKOJBOEMAA_proto_rawDescGZIP() []byte {
	file_OAKOJBOEMAA_proto_rawDescOnce.Do(func() {
		file_OAKOJBOEMAA_proto_rawDescData = protoimpl.X.CompressGZIP(file_OAKOJBOEMAA_proto_rawDescData)
	})
	return file_OAKOJBOEMAA_proto_rawDescData
}

var file_OAKOJBOEMAA_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_OAKOJBOEMAA_proto_goTypes = []interface{}{
	(*OAKOJBOEMAA)(nil), // 0: OAKOJBOEMAA
	(*Vector)(nil),      // 1: Vector
	(*GPDFECLFNHM)(nil), // 2: GPDFECLFNHM
}
var file_OAKOJBOEMAA_proto_depIdxs = []int32{
	1, // 0: OAKOJBOEMAA.PBPDGAMKBPM:type_name -> Vector
	2, // 1: OAKOJBOEMAA.MJINOEJMBON:type_name -> GPDFECLFNHM
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_OAKOJBOEMAA_proto_init() }
func file_OAKOJBOEMAA_proto_init() {
	if File_OAKOJBOEMAA_proto != nil {
		return
	}
	file_GPDFECLFNHM_proto_init()
	file_Vector_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_OAKOJBOEMAA_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OAKOJBOEMAA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_OAKOJBOEMAA_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_OAKOJBOEMAA_proto_goTypes,
		DependencyIndexes: file_OAKOJBOEMAA_proto_depIdxs,
		MessageInfos:      file_OAKOJBOEMAA_proto_msgTypes,
	}.Build()
	File_OAKOJBOEMAA_proto = out.File
	file_OAKOJBOEMAA_proto_rawDesc = nil
	file_OAKOJBOEMAA_proto_goTypes = nil
	file_OAKOJBOEMAA_proto_depIdxs = nil
}
