// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: OBFKMALBGML.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OBFKMALBGML struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FIDCCOAADCP uint32 `protobuf:"varint,7,opt,name=FIDCCOAADCP,proto3" json:"FIDCCOAADCP,omitempty"`
	DJBJKBEMKMD uint32 `protobuf:"varint,15,opt,name=DJBJKBEMKMD,proto3" json:"DJBJKBEMKMD,omitempty"`
	OAOKDFJPPDN uint32 `protobuf:"varint,3,opt,name=OAOKDFJPPDN,proto3" json:"OAOKDFJPPDN,omitempty"`
	KDPKIILLCDC uint32 `protobuf:"varint,6,opt,name=KDPKIILLCDC,proto3" json:"KDPKIILLCDC,omitempty"`
}

func (x *OBFKMALBGML) Reset() {
	*x = OBFKMALBGML{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OBFKMALBGML_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OBFKMALBGML) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OBFKMALBGML) ProtoMessage() {}

func (x *OBFKMALBGML) ProtoReflect() protoreflect.Message {
	mi := &file_OBFKMALBGML_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OBFKMALBGML.ProtoReflect.Descriptor instead.
func (*OBFKMALBGML) Descriptor() ([]byte, []int) {
	return file_OBFKMALBGML_proto_rawDescGZIP(), []int{0}
}

func (x *OBFKMALBGML) GetFIDCCOAADCP() uint32 {
	if x != nil {
		return x.FIDCCOAADCP
	}
	return 0
}

func (x *OBFKMALBGML) GetDJBJKBEMKMD() uint32 {
	if x != nil {
		return x.DJBJKBEMKMD
	}
	return 0
}

func (x *OBFKMALBGML) GetOAOKDFJPPDN() uint32 {
	if x != nil {
		return x.OAOKDFJPPDN
	}
	return 0
}

func (x *OBFKMALBGML) GetKDPKIILLCDC() uint32 {
	if x != nil {
		return x.KDPKIILLCDC
	}
	return 0
}

var File_OBFKMALBGML_proto protoreflect.FileDescriptor

var file_OBFKMALBGML_proto_rawDesc = []byte{
	0x0a, 0x11, 0x4f, 0x42, 0x46, 0x4b, 0x4d, 0x41, 0x4c, 0x42, 0x47, 0x4d, 0x4c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x95, 0x01, 0x0a, 0x0b, 0x4f, 0x42, 0x46, 0x4b, 0x4d, 0x41, 0x4c, 0x42,
	0x47, 0x4d, 0x4c, 0x12, 0x20, 0x0a, 0x0b, 0x46, 0x49, 0x44, 0x43, 0x43, 0x4f, 0x41, 0x41, 0x44,
	0x43, 0x50, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x46, 0x49, 0x44, 0x43, 0x43, 0x4f,
	0x41, 0x41, 0x44, 0x43, 0x50, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x4a, 0x42, 0x4a, 0x4b, 0x42, 0x45,
	0x4d, 0x4b, 0x4d, 0x44, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x44, 0x4a, 0x42, 0x4a,
	0x4b, 0x42, 0x45, 0x4d, 0x4b, 0x4d, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x41, 0x4f, 0x4b, 0x44,
	0x46, 0x4a, 0x50, 0x50, 0x44, 0x4e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x4f, 0x41,
	0x4f, 0x4b, 0x44, 0x46, 0x4a, 0x50, 0x50, 0x44, 0x4e, 0x12, 0x20, 0x0a, 0x0b, 0x4b, 0x44, 0x50,
	0x4b, 0x49, 0x49, 0x4c, 0x4c, 0x43, 0x44, 0x43, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x4b, 0x44, 0x50, 0x4b, 0x49, 0x49, 0x4c, 0x4c, 0x43, 0x44, 0x43, 0x42, 0x28, 0x5a, 0x08, 0x2e,
	0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x1b, 0x45, 0x67, 0x67, 0x4c, 0x69, 0x6e,
	0x6b, 0x2e, 0x44, 0x61, 0x6e, 0x68, 0x65, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_OBFKMALBGML_proto_rawDescOnce sync.Once
	file_OBFKMALBGML_proto_rawDescData = file_OBFKMALBGML_proto_rawDesc
)

func file_OBFKMALBGML_proto_rawDescGZIP() []byte {
	file_OBFKMALBGML_proto_rawDescOnce.Do(func() {
		file_OBFKMALBGML_proto_rawDescData = protoimpl.X.CompressGZIP(file_OBFKMALBGML_proto_rawDescData)
	})
	return file_OBFKMALBGML_proto_rawDescData
}

var file_OBFKMALBGML_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_OBFKMALBGML_proto_goTypes = []interface{}{
	(*OBFKMALBGML)(nil), // 0: OBFKMALBGML
}
var file_OBFKMALBGML_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_OBFKMALBGML_proto_init() }
func file_OBFKMALBGML_proto_init() {
	if File_OBFKMALBGML_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_OBFKMALBGML_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OBFKMALBGML); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_OBFKMALBGML_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_OBFKMALBGML_proto_goTypes,
		DependencyIndexes: file_OBFKMALBGML_proto_depIdxs,
		MessageInfos:      file_OBFKMALBGML_proto_msgTypes,
	}.Build()
	File_OBFKMALBGML_proto = out.File
	file_OBFKMALBGML_proto_rawDesc = nil
	file_OBFKMALBGML_proto_goTypes = nil
	file_OBFKMALBGML_proto_depIdxs = nil
}
