// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: PlayingState.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayingState int32

const (
	PlayingState_PLAYING_STATE_NONE       PlayingState = 0
	PlayingState_PLAYING_ROGUE_COSMOS     PlayingState = 1
	PlayingState_PLAYING_ROGUE_CHESS      PlayingState = 2
	PlayingState_PLAYING_ROGUE_CHESS_NOUS PlayingState = 3
	PlayingState_PLAYING_CHALLENGE_MEMORY PlayingState = 4
	PlayingState_PLAYING_CHALLENGE_STORY  PlayingState = 5
)

// Enum value maps for PlayingState.
var (
	PlayingState_name = map[int32]string{
		0: "PLAYING_STATE_NONE",
		1: "PLAYING_ROGUE_COSMOS",
		2: "PLAYING_ROGUE_CHESS",
		3: "PLAYING_ROGUE_CHESS_NOUS",
		4: "PLAYING_CHALLENGE_MEMORY",
		5: "PLAYING_CHALLENGE_STORY",
	}
	PlayingState_value = map[string]int32{
		"PLAYING_STATE_NONE":       0,
		"PLAYING_ROGUE_COSMOS":     1,
		"PLAYING_ROGUE_CHESS":      2,
		"PLAYING_ROGUE_CHESS_NOUS": 3,
		"PLAYING_CHALLENGE_MEMORY": 4,
		"PLAYING_CHALLENGE_STORY":  5,
	}
)

func (x PlayingState) Enum() *PlayingState {
	p := new(PlayingState)
	*p = x
	return p
}

func (x PlayingState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayingState) Descriptor() protoreflect.EnumDescriptor {
	return file_PlayingState_proto_enumTypes[0].Descriptor()
}

func (PlayingState) Type() protoreflect.EnumType {
	return &file_PlayingState_proto_enumTypes[0]
}

func (x PlayingState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayingState.Descriptor instead.
func (PlayingState) EnumDescriptor() ([]byte, []int) {
	return file_PlayingState_proto_rawDescGZIP(), []int{0}
}

var File_PlayingState_proto protoreflect.FileDescriptor

var file_PlayingState_proto_rawDesc = []byte{
	0x0a, 0x12, 0x50, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2a, 0xb2, 0x01, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x4c, 0x41, 0x59, 0x49, 0x4e, 0x47,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x18, 0x0a,
	0x14, 0x50, 0x4c, 0x41, 0x59, 0x49, 0x4e, 0x47, 0x5f, 0x52, 0x4f, 0x47, 0x55, 0x45, 0x5f, 0x43,
	0x4f, 0x53, 0x4d, 0x4f, 0x53, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x50, 0x4c, 0x41, 0x59, 0x49,
	0x4e, 0x47, 0x5f, 0x52, 0x4f, 0x47, 0x55, 0x45, 0x5f, 0x43, 0x48, 0x45, 0x53, 0x53, 0x10, 0x02,
	0x12, 0x1c, 0x0a, 0x18, 0x50, 0x4c, 0x41, 0x59, 0x49, 0x4e, 0x47, 0x5f, 0x52, 0x4f, 0x47, 0x55,
	0x45, 0x5f, 0x43, 0x48, 0x45, 0x53, 0x53, 0x5f, 0x4e, 0x4f, 0x55, 0x53, 0x10, 0x03, 0x12, 0x1c,
	0x0a, 0x18, 0x50, 0x4c, 0x41, 0x59, 0x49, 0x4e, 0x47, 0x5f, 0x43, 0x48, 0x41, 0x4c, 0x4c, 0x45,
	0x4e, 0x47, 0x45, 0x5f, 0x4d, 0x45, 0x4d, 0x4f, 0x52, 0x59, 0x10, 0x04, 0x12, 0x1b, 0x0a, 0x17,
	0x50, 0x4c, 0x41, 0x59, 0x49, 0x4e, 0x47, 0x5f, 0x43, 0x48, 0x41, 0x4c, 0x4c, 0x45, 0x4e, 0x47,
	0x45, 0x5f, 0x53, 0x54, 0x4f, 0x52, 0x59, 0x10, 0x05, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_PlayingState_proto_rawDescOnce sync.Once
	file_PlayingState_proto_rawDescData = file_PlayingState_proto_rawDesc
)

func file_PlayingState_proto_rawDescGZIP() []byte {
	file_PlayingState_proto_rawDescOnce.Do(func() {
		file_PlayingState_proto_rawDescData = protoimpl.X.CompressGZIP(file_PlayingState_proto_rawDescData)
	})
	return file_PlayingState_proto_rawDescData
}

var file_PlayingState_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_PlayingState_proto_goTypes = []interface{}{
	(PlayingState)(0), // 0: PlayingState
}
var file_PlayingState_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PlayingState_proto_init() }
func file_PlayingState_proto_init() {
	if File_PlayingState_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PlayingState_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PlayingState_proto_goTypes,
		DependencyIndexes: file_PlayingState_proto_depIdxs,
		EnumInfos:         file_PlayingState_proto_enumTypes,
	}.Build()
	File_PlayingState_proto = out.File
	file_PlayingState_proto_rawDesc = nil
	file_PlayingState_proto_goTypes = nil
	file_PlayingState_proto_depIdxs = nil
}
