// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: PlayerCollectionInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerCollectionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LJJHBMHGNBL uint32 `protobuf:"varint,5,opt,name=LJJHBMHGNBL,proto3" json:"LJJHBMHGNBL,omitempty"`
	NHIEMDHCMOE uint32 `protobuf:"varint,4,opt,name=NHIEMDHCMOE,proto3" json:"NHIEMDHCMOE,omitempty"`
	OFGKGCHGECA uint32 `protobuf:"varint,13,opt,name=OFGKGCHGECA,proto3" json:"OFGKGCHGECA,omitempty"`
	OOHGFCAKDOI uint32 `protobuf:"varint,1,opt,name=OOHGFCAKDOI,proto3" json:"OOHGFCAKDOI,omitempty"`
	LGGDDDLGLIG uint32 `protobuf:"varint,6,opt,name=LGGDDDLGLIG,proto3" json:"LGGDDDLGLIG,omitempty"`
}

func (x *PlayerCollectionInfo) Reset() {
	*x = PlayerCollectionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PlayerCollectionInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerCollectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerCollectionInfo) ProtoMessage() {}

func (x *PlayerCollectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_PlayerCollectionInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerCollectionInfo.ProtoReflect.Descriptor instead.
func (*PlayerCollectionInfo) Descriptor() ([]byte, []int) {
	return file_PlayerCollectionInfo_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerCollectionInfo) GetLJJHBMHGNBL() uint32 {
	if x != nil {
		return x.LJJHBMHGNBL
	}
	return 0
}

func (x *PlayerCollectionInfo) GetNHIEMDHCMOE() uint32 {
	if x != nil {
		return x.NHIEMDHCMOE
	}
	return 0
}

func (x *PlayerCollectionInfo) GetOFGKGCHGECA() uint32 {
	if x != nil {
		return x.OFGKGCHGECA
	}
	return 0
}

func (x *PlayerCollectionInfo) GetOOHGFCAKDOI() uint32 {
	if x != nil {
		return x.OOHGFCAKDOI
	}
	return 0
}

func (x *PlayerCollectionInfo) GetLGGDDDLGLIG() uint32 {
	if x != nil {
		return x.LGGDDDLGLIG
	}
	return 0
}

var File_PlayerCollectionInfo_proto protoreflect.FileDescriptor

var file_PlayerCollectionInfo_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc0, 0x01, 0x0a,
	0x14, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x4c, 0x4a, 0x4a, 0x48, 0x42, 0x4d, 0x48,
	0x47, 0x4e, 0x42, 0x4c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x4c, 0x4a, 0x4a, 0x48,
	0x42, 0x4d, 0x48, 0x47, 0x4e, 0x42, 0x4c, 0x12, 0x20, 0x0a, 0x0b, 0x4e, 0x48, 0x49, 0x45, 0x4d,
	0x44, 0x48, 0x43, 0x4d, 0x4f, 0x45, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x4e, 0x48,
	0x49, 0x45, 0x4d, 0x44, 0x48, 0x43, 0x4d, 0x4f, 0x45, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x46, 0x47,
	0x4b, 0x47, 0x43, 0x48, 0x47, 0x45, 0x43, 0x41, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x4f, 0x46, 0x47, 0x4b, 0x47, 0x43, 0x48, 0x47, 0x45, 0x43, 0x41, 0x12, 0x20, 0x0a, 0x0b, 0x4f,
	0x4f, 0x48, 0x47, 0x46, 0x43, 0x41, 0x4b, 0x44, 0x4f, 0x49, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x4f, 0x4f, 0x48, 0x47, 0x46, 0x43, 0x41, 0x4b, 0x44, 0x4f, 0x49, 0x12, 0x20, 0x0a,
	0x0b, 0x4c, 0x47, 0x47, 0x44, 0x44, 0x44, 0x4c, 0x47, 0x4c, 0x49, 0x47, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0b, 0x4c, 0x47, 0x47, 0x44, 0x44, 0x44, 0x4c, 0x47, 0x4c, 0x49, 0x47, 0x42,
	0x2e, 0x5a, 0x0e, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0xaa, 0x02, 0x1b, 0x45, 0x67, 0x67, 0x4c, 0x69, 0x6e, 0x6b, 0x2e, 0x44, 0x61, 0x6e, 0x68,
	0x65, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_PlayerCollectionInfo_proto_rawDescOnce sync.Once
	file_PlayerCollectionInfo_proto_rawDescData = file_PlayerCollectionInfo_proto_rawDesc
)

func file_PlayerCollectionInfo_proto_rawDescGZIP() []byte {
	file_PlayerCollectionInfo_proto_rawDescOnce.Do(func() {
		file_PlayerCollectionInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_PlayerCollectionInfo_proto_rawDescData)
	})
	return file_PlayerCollectionInfo_proto_rawDescData
}

var file_PlayerCollectionInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PlayerCollectionInfo_proto_goTypes = []interface{}{
	(*PlayerCollectionInfo)(nil), // 0: PlayerCollectionInfo
}
var file_PlayerCollectionInfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PlayerCollectionInfo_proto_init() }
func file_PlayerCollectionInfo_proto_init() {
	if File_PlayerCollectionInfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_PlayerCollectionInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerCollectionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PlayerCollectionInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PlayerCollectionInfo_proto_goTypes,
		DependencyIndexes: file_PlayerCollectionInfo_proto_depIdxs,
		MessageInfos:      file_PlayerCollectionInfo_proto_msgTypes,
	}.Build()
	File_PlayerCollectionInfo_proto = out.File
	file_PlayerCollectionInfo_proto_rawDesc = nil
	file_PlayerCollectionInfo_proto_goTypes = nil
	file_PlayerCollectionInfo_proto_depIdxs = nil
}
