// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: QuitLineupCsReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuitLineupCsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseAvatarId    uint32          `protobuf:"varint,5,opt,name=base_avatar_id,json=baseAvatarId,proto3" json:"base_avatar_id,omitempty"`
	ExtraLineupType ExtraLineupType `protobuf:"varint,7,opt,name=extra_lineup_type,json=extraLineupType,proto3,enum=ExtraLineupType" json:"extra_lineup_type,omitempty"`
	AvatarType      AvatarType      `protobuf:"varint,6,opt,name=avatar_type,json=avatarType,proto3,enum=AvatarType" json:"avatar_type,omitempty"`
	Index           uint32          `protobuf:"varint,10,opt,name=index,proto3" json:"index,omitempty"`
	IsVirtual       bool            `protobuf:"varint,14,opt,name=is_virtual,json=isVirtual,proto3" json:"is_virtual,omitempty"`
	PlaneId         uint32          `protobuf:"varint,15,opt,name=plane_id,json=planeId,proto3" json:"plane_id,omitempty"`
}

func (x *QuitLineupCsReq) Reset() {
	*x = QuitLineupCsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_QuitLineupCsReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuitLineupCsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitLineupCsReq) ProtoMessage() {}

func (x *QuitLineupCsReq) ProtoReflect() protoreflect.Message {
	mi := &file_QuitLineupCsReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitLineupCsReq.ProtoReflect.Descriptor instead.
func (*QuitLineupCsReq) Descriptor() ([]byte, []int) {
	return file_QuitLineupCsReq_proto_rawDescGZIP(), []int{0}
}

func (x *QuitLineupCsReq) GetBaseAvatarId() uint32 {
	if x != nil {
		return x.BaseAvatarId
	}
	return 0
}

func (x *QuitLineupCsReq) GetExtraLineupType() ExtraLineupType {
	if x != nil {
		return x.ExtraLineupType
	}
	return ExtraLineupType_LINEUP_NONE
}

func (x *QuitLineupCsReq) GetAvatarType() AvatarType {
	if x != nil {
		return x.AvatarType
	}
	return AvatarType_AVATAR_TYPE_NONE
}

func (x *QuitLineupCsReq) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *QuitLineupCsReq) GetIsVirtual() bool {
	if x != nil {
		return x.IsVirtual
	}
	return false
}

func (x *QuitLineupCsReq) GetPlaneId() uint32 {
	if x != nil {
		return x.PlaneId
	}
	return 0
}

var File_QuitLineupCsReq_proto protoreflect.FileDescriptor

var file_QuitLineupCsReq_proto_rawDesc = []byte{
	0x0a, 0x15, 0x51, 0x75, 0x69, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x75, 0x70, 0x43, 0x73, 0x52, 0x65,
	0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x45, 0x78, 0x74, 0x72, 0x61, 0x4c, 0x69,
	0x6e, 0x65, 0x75, 0x70, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10,
	0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xf3, 0x01, 0x0a, 0x0f, 0x51, 0x75, 0x69, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x75, 0x70, 0x43,
	0x73, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x0e, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x62, 0x61,
	0x73, 0x65, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x11, 0x65, 0x78,
	0x74, 0x72, 0x61, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x75, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x4c, 0x69, 0x6e,
	0x65, 0x75, 0x70, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0f, 0x65, 0x78, 0x74, 0x72, 0x61, 0x4c, 0x69,
	0x6e, 0x65, 0x75, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2c, 0x0a, 0x0b, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e,
	0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1d, 0x0a, 0x0a,
	0x69, 0x73, 0x5f, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x69, 0x73, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x70,
	0x6c, 0x61, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x70,
	0x6c, 0x61, 0x6e, 0x65, 0x49, 0x64, 0x42, 0x28, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0xaa, 0x02, 0x1b, 0x45, 0x67, 0x67, 0x4c, 0x69, 0x6e, 0x6b, 0x2e, 0x44, 0x61, 0x6e,
	0x68, 0x65, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_QuitLineupCsReq_proto_rawDescOnce sync.Once
	file_QuitLineupCsReq_proto_rawDescData = file_QuitLineupCsReq_proto_rawDesc
)

func file_QuitLineupCsReq_proto_rawDescGZIP() []byte {
	file_QuitLineupCsReq_proto_rawDescOnce.Do(func() {
		file_QuitLineupCsReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_QuitLineupCsReq_proto_rawDescData)
	})
	return file_QuitLineupCsReq_proto_rawDescData
}

var file_QuitLineupCsReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_QuitLineupCsReq_proto_goTypes = []interface{}{
	(*QuitLineupCsReq)(nil), // 0: QuitLineupCsReq
	(ExtraLineupType)(0),    // 1: ExtraLineupType
	(AvatarType)(0),         // 2: AvatarType
}
var file_QuitLineupCsReq_proto_depIdxs = []int32{
	1, // 0: QuitLineupCsReq.extra_lineup_type:type_name -> ExtraLineupType
	2, // 1: QuitLineupCsReq.avatar_type:type_name -> AvatarType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_QuitLineupCsReq_proto_init() }
func file_QuitLineupCsReq_proto_init() {
	if File_QuitLineupCsReq_proto != nil {
		return
	}
	file_ExtraLineupType_proto_init()
	file_AvatarType_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_QuitLineupCsReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuitLineupCsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_QuitLineupCsReq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_QuitLineupCsReq_proto_goTypes,
		DependencyIndexes: file_QuitLineupCsReq_proto_depIdxs,
		MessageInfos:      file_QuitLineupCsReq_proto_msgTypes,
	}.Build()
	File_QuitLineupCsReq_proto = out.File
	file_QuitLineupCsReq_proto_rawDesc = nil
	file_QuitLineupCsReq_proto_goTypes = nil
	file_QuitLineupCsReq_proto_depIdxs = nil
}
