// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: QuitLineupScRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuitLineupScRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode      uint32 `protobuf:"varint,8,opt,name=retcode,proto3" json:"retcode,omitempty"`
	PlaneId      uint32 `protobuf:"varint,7,opt,name=plane_id,json=planeId,proto3" json:"plane_id,omitempty"`
	BaseAvatarId uint32 `protobuf:"varint,11,opt,name=base_avatar_id,json=baseAvatarId,proto3" json:"base_avatar_id,omitempty"`
	IsMainline   bool   `protobuf:"varint,4,opt,name=is_mainline,json=isMainline,proto3" json:"is_mainline,omitempty"`
	IsVirtual    bool   `protobuf:"varint,14,opt,name=is_virtual,json=isVirtual,proto3" json:"is_virtual,omitempty"`
}

func (x *QuitLineupScRsp) Reset() {
	*x = QuitLineupScRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_QuitLineupScRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuitLineupScRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitLineupScRsp) ProtoMessage() {}

func (x *QuitLineupScRsp) ProtoReflect() protoreflect.Message {
	mi := &file_QuitLineupScRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitLineupScRsp.ProtoReflect.Descriptor instead.
func (*QuitLineupScRsp) Descriptor() ([]byte, []int) {
	return file_QuitLineupScRsp_proto_rawDescGZIP(), []int{0}
}

func (x *QuitLineupScRsp) GetRetcode() uint32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *QuitLineupScRsp) GetPlaneId() uint32 {
	if x != nil {
		return x.PlaneId
	}
	return 0
}

func (x *QuitLineupScRsp) GetBaseAvatarId() uint32 {
	if x != nil {
		return x.BaseAvatarId
	}
	return 0
}

func (x *QuitLineupScRsp) GetIsMainline() bool {
	if x != nil {
		return x.IsMainline
	}
	return false
}

func (x *QuitLineupScRsp) GetIsVirtual() bool {
	if x != nil {
		return x.IsVirtual
	}
	return false
}

var File_QuitLineupScRsp_proto protoreflect.FileDescriptor

var file_QuitLineupScRsp_proto_rawDesc = []byte{
	0x0a, 0x15, 0x51, 0x75, 0x69, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x75, 0x70, 0x53, 0x63, 0x52, 0x73,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xac, 0x01, 0x0a, 0x0f, 0x51, 0x75, 0x69, 0x74,
	0x4c, 0x69, 0x6e, 0x65, 0x75, 0x70, 0x53, 0x63, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x65,
	0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x49, 0x64,
	0x12, 0x24, 0x0a, 0x0e, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x41, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x6d, 0x61, 0x69,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x4d,
	0x61, 0x69, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x76, 0x69,
	0x72, 0x74, 0x75, 0x61, 0x6c, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x56,
	0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x42, 0x28, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0xaa, 0x02, 0x1b, 0x45, 0x67, 0x67, 0x4c, 0x69, 0x6e, 0x6b, 0x2e, 0x44, 0x61, 0x6e,
	0x68, 0x65, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_QuitLineupScRsp_proto_rawDescOnce sync.Once
	file_QuitLineupScRsp_proto_rawDescData = file_QuitLineupScRsp_proto_rawDesc
)

func file_QuitLineupScRsp_proto_rawDescGZIP() []byte {
	file_QuitLineupScRsp_proto_rawDescOnce.Do(func() {
		file_QuitLineupScRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_QuitLineupScRsp_proto_rawDescData)
	})
	return file_QuitLineupScRsp_proto_rawDescData
}

var file_QuitLineupScRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_QuitLineupScRsp_proto_goTypes = []interface{}{
	(*QuitLineupScRsp)(nil), // 0: QuitLineupScRsp
}
var file_QuitLineupScRsp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_QuitLineupScRsp_proto_init() }
func file_QuitLineupScRsp_proto_init() {
	if File_QuitLineupScRsp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_QuitLineupScRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuitLineupScRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_QuitLineupScRsp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_QuitLineupScRsp_proto_goTypes,
		DependencyIndexes: file_QuitLineupScRsp_proto_depIdxs,
		MessageInfos:      file_QuitLineupScRsp_proto_msgTypes,
	}.Build()
	File_QuitLineupScRsp_proto = out.File
	file_QuitLineupScRsp_proto_rawDesc = nil
	file_QuitLineupScRsp_proto_goTypes = nil
	file_QuitLineupScRsp_proto_depIdxs = nil
}
