// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: RacingData.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RacingData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxScore    uint32          `protobuf:"varint,15,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"` // 12
	Type        MovieRacingType `protobuf:"varint,10,opt,name=type,proto3,enum=MovieRacingType" json:"type,omitempty"`
	FFBPNMGCKNF uint32          `protobuf:"varint,12,opt,name=FFBPNMGCKNF,proto3" json:"FFBPNMGCKNF,omitempty"`
	Level       uint32          `protobuf:"varint,7,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *RacingData) Reset() {
	*x = RacingData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RacingData_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RacingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RacingData) ProtoMessage() {}

func (x *RacingData) ProtoReflect() protoreflect.Message {
	mi := &file_RacingData_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RacingData.ProtoReflect.Descriptor instead.
func (*RacingData) Descriptor() ([]byte, []int) {
	return file_RacingData_proto_rawDescGZIP(), []int{0}
}

func (x *RacingData) GetMaxScore() uint32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *RacingData) GetType() MovieRacingType {
	if x != nil {
		return x.Type
	}
	return MovieRacingType_MOVIE_RACING_OVER_TAKE
}

func (x *RacingData) GetFFBPNMGCKNF() uint32 {
	if x != nil {
		return x.FFBPNMGCKNF
	}
	return 0
}

func (x *RacingData) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

var File_RacingData_proto protoreflect.FileDescriptor

var file_RacingData_proto_rawDesc = []byte{
	0x0a, 0x10, 0x52, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x15, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x54,
	0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x01, 0x0a, 0x0a, 0x52, 0x61,
	0x63, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x5f,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6d, 0x61, 0x78,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x61, 0x63, 0x69, 0x6e,
	0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x46,
	0x46, 0x42, 0x50, 0x4e, 0x4d, 0x47, 0x43, 0x4b, 0x4e, 0x46, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x46, 0x46, 0x42, 0x50, 0x4e, 0x4d, 0x47, 0x43, 0x4b, 0x4e, 0x46, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x42, 0x28, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xaa,
	0x02, 0x1b, 0x45, 0x67, 0x67, 0x4c, 0x69, 0x6e, 0x6b, 0x2e, 0x44, 0x61, 0x6e, 0x68, 0x65, 0x6e,
	0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_RacingData_proto_rawDescOnce sync.Once
	file_RacingData_proto_rawDescData = file_RacingData_proto_rawDesc
)

func file_RacingData_proto_rawDescGZIP() []byte {
	file_RacingData_proto_rawDescOnce.Do(func() {
		file_RacingData_proto_rawDescData = protoimpl.X.CompressGZIP(file_RacingData_proto_rawDescData)
	})
	return file_RacingData_proto_rawDescData
}

var file_RacingData_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_RacingData_proto_goTypes = []interface{}{
	(*RacingData)(nil),   // 0: RacingData
	(MovieRacingType)(0), // 1: MovieRacingType
}
var file_RacingData_proto_depIdxs = []int32{
	1, // 0: RacingData.type:type_name -> MovieRacingType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_RacingData_proto_init() }
func file_RacingData_proto_init() {
	if File_RacingData_proto != nil {
		return
	}
	file_MovieRacingType_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_RacingData_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RacingData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_RacingData_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RacingData_proto_goTypes,
		DependencyIndexes: file_RacingData_proto_depIdxs,
		MessageInfos:      file_RacingData_proto_msgTypes,
	}.Build()
	File_RacingData_proto = out.File
	file_RacingData_proto_rawDesc = nil
	file_RacingData_proto_goTypes = nil
	file_RacingData_proto_depIdxs = nil
}
