// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: RaidCollectionEnterNextRaidScRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RaidCollectionEnterNextRaidScRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scene   *DNLBHACEIAL `protobuf:"bytes,7,opt,name=scene,proto3" json:"scene,omitempty"`
	Retcode uint32       `protobuf:"varint,13,opt,name=retcode,proto3" json:"retcode,omitempty"`
}

func (x *RaidCollectionEnterNextRaidScRsp) Reset() {
	*x = RaidCollectionEnterNextRaidScRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RaidCollectionEnterNextRaidScRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RaidCollectionEnterNextRaidScRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaidCollectionEnterNextRaidScRsp) ProtoMessage() {}

func (x *RaidCollectionEnterNextRaidScRsp) ProtoReflect() protoreflect.Message {
	mi := &file_RaidCollectionEnterNextRaidScRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaidCollectionEnterNextRaidScRsp.ProtoReflect.Descriptor instead.
func (*RaidCollectionEnterNextRaidScRsp) Descriptor() ([]byte, []int) {
	return file_RaidCollectionEnterNextRaidScRsp_proto_rawDescGZIP(), []int{0}
}

func (x *RaidCollectionEnterNextRaidScRsp) GetScene() *DNLBHACEIAL {
	if x != nil {
		return x.Scene
	}
	return nil
}

func (x *RaidCollectionEnterNextRaidScRsp) GetRetcode() uint32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

var File_RaidCollectionEnterNextRaidScRsp_proto protoreflect.FileDescriptor

var file_RaidCollectionEnterNextRaidScRsp_proto_rawDesc = []byte{
	0x0a, 0x26, 0x52, 0x61, 0x69, 0x64, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x4e, 0x65, 0x78, 0x74, 0x52, 0x61, 0x69, 0x64, 0x53, 0x63, 0x52,
	0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x44, 0x4e, 0x4c, 0x42, 0x48, 0x41,
	0x43, 0x45, 0x49, 0x41, 0x4c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a, 0x20, 0x52,
	0x61, 0x69, 0x64, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74,
	0x65, 0x72, 0x4e, 0x65, 0x78, 0x74, 0x52, 0x61, 0x69, 0x64, 0x53, 0x63, 0x52, 0x73, 0x70, 0x12,
	0x22, 0x0a, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x44, 0x4e, 0x4c, 0x42, 0x48, 0x41, 0x43, 0x45, 0x49, 0x41, 0x4c, 0x52, 0x05, 0x73, 0x63,
	0x65, 0x6e, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x2e, 0x5a,
	0x0e, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xaa,
	0x02, 0x1b, 0x45, 0x67, 0x67, 0x4c, 0x69, 0x6e, 0x6b, 0x2e, 0x44, 0x61, 0x6e, 0x68, 0x65, 0x6e,
	0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_RaidCollectionEnterNextRaidScRsp_proto_rawDescOnce sync.Once
	file_RaidCollectionEnterNextRaidScRsp_proto_rawDescData = file_RaidCollectionEnterNextRaidScRsp_proto_rawDesc
)

func file_RaidCollectionEnterNextRaidScRsp_proto_rawDescGZIP() []byte {
	file_RaidCollectionEnterNextRaidScRsp_proto_rawDescOnce.Do(func() {
		file_RaidCollectionEnterNextRaidScRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_RaidCollectionEnterNextRaidScRsp_proto_rawDescData)
	})
	return file_RaidCollectionEnterNextRaidScRsp_proto_rawDescData
}

var file_RaidCollectionEnterNextRaidScRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_RaidCollectionEnterNextRaidScRsp_proto_goTypes = []interface{}{
	(*RaidCollectionEnterNextRaidScRsp)(nil), // 0: RaidCollectionEnterNextRaidScRsp
	(*DNLBHACEIAL)(nil),                      // 1: DNLBHACEIAL
}
var file_RaidCollectionEnterNextRaidScRsp_proto_depIdxs = []int32{
	1, // 0: RaidCollectionEnterNextRaidScRsp.scene:type_name -> DNLBHACEIAL
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_RaidCollectionEnterNextRaidScRsp_proto_init() }
func file_RaidCollectionEnterNextRaidScRsp_proto_init() {
	if File_RaidCollectionEnterNextRaidScRsp_proto != nil {
		return
	}
	file_DNLBHACEIAL_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_RaidCollectionEnterNextRaidScRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RaidCollectionEnterNextRaidScRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_RaidCollectionEnterNextRaidScRsp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RaidCollectionEnterNextRaidScRsp_proto_goTypes,
		DependencyIndexes: file_RaidCollectionEnterNextRaidScRsp_proto_depIdxs,
		MessageInfos:      file_RaidCollectionEnterNextRaidScRsp_proto_msgTypes,
	}.Build()
	File_RaidCollectionEnterNextRaidScRsp_proto = out.File
	file_RaidCollectionEnterNextRaidScRsp_proto_rawDesc = nil
	file_RaidCollectionEnterNextRaidScRsp_proto_goTypes = nil
	file_RaidCollectionEnterNextRaidScRsp_proto_depIdxs = nil
}
