// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: ResetMapRotationRegionCsReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResetMapRotationRegionCsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Motion  *MotionInfo  `protobuf:"bytes,4,opt,name=motion,proto3" json:"motion,omitempty"`
	MapInfo *IJJHKDNFKMD `protobuf:"bytes,14,opt,name=map_info,json=mapInfo,proto3" json:"map_info,omitempty"`
}

func (x *ResetMapRotationRegionCsReq) Reset() {
	*x = ResetMapRotationRegionCsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ResetMapRotationRegionCsReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetMapRotationRegionCsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetMapRotationRegionCsReq) ProtoMessage() {}

func (x *ResetMapRotationRegionCsReq) ProtoReflect() protoreflect.Message {
	mi := &file_ResetMapRotationRegionCsReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetMapRotationRegionCsReq.ProtoReflect.Descriptor instead.
func (*ResetMapRotationRegionCsReq) Descriptor() ([]byte, []int) {
	return file_ResetMapRotationRegionCsReq_proto_rawDescGZIP(), []int{0}
}

func (x *ResetMapRotationRegionCsReq) GetMotion() *MotionInfo {
	if x != nil {
		return x.Motion
	}
	return nil
}

func (x *ResetMapRotationRegionCsReq) GetMapInfo() *IJJHKDNFKMD {
	if x != nil {
		return x.MapInfo
	}
	return nil
}

var File_ResetMapRotationRegionCsReq_proto protoreflect.FileDescriptor

var file_ResetMapRotationRegionCsReq_proto_rawDesc = []byte{
	0x0a, 0x21, 0x52, 0x65, 0x73, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x43, 0x73, 0x52, 0x65, 0x71, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x49, 0x4a, 0x4a, 0x48, 0x4b, 0x44, 0x4e, 0x46, 0x4b, 0x4d, 0x44,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x4d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6b, 0x0a, 0x1b, 0x52, 0x65, 0x73, 0x65,
	0x74, 0x4d, 0x61, 0x70, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x43, 0x73, 0x52, 0x65, 0x71, 0x12, 0x23, 0x0a, 0x06, 0x6d, 0x6f, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4d, 0x6f, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x08,
	0x6d, 0x61, 0x70, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x49, 0x4a, 0x4a, 0x48, 0x4b, 0x44, 0x4e, 0x46, 0x4b, 0x4d, 0x44, 0x52, 0x07, 0x6d, 0x61,
	0x70, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x28, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0xaa, 0x02, 0x1b, 0x45, 0x67, 0x67, 0x4c, 0x69, 0x6e, 0x6b, 0x2e, 0x44, 0x61, 0x6e, 0x68,
	0x65, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ResetMapRotationRegionCsReq_proto_rawDescOnce sync.Once
	file_ResetMapRotationRegionCsReq_proto_rawDescData = file_ResetMapRotationRegionCsReq_proto_rawDesc
)

func file_ResetMapRotationRegionCsReq_proto_rawDescGZIP() []byte {
	file_ResetMapRotationRegionCsReq_proto_rawDescOnce.Do(func() {
		file_ResetMapRotationRegionCsReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_ResetMapRotationRegionCsReq_proto_rawDescData)
	})
	return file_ResetMapRotationRegionCsReq_proto_rawDescData
}

var file_ResetMapRotationRegionCsReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ResetMapRotationRegionCsReq_proto_goTypes = []interface{}{
	(*ResetMapRotationRegionCsReq)(nil), // 0: ResetMapRotationRegionCsReq
	(*MotionInfo)(nil),                  // 1: MotionInfo
	(*IJJHKDNFKMD)(nil),                 // 2: IJJHKDNFKMD
}
var file_ResetMapRotationRegionCsReq_proto_depIdxs = []int32{
	1, // 0: ResetMapRotationRegionCsReq.motion:type_name -> MotionInfo
	2, // 1: ResetMapRotationRegionCsReq.map_info:type_name -> IJJHKDNFKMD
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ResetMapRotationRegionCsReq_proto_init() }
func file_ResetMapRotationRegionCsReq_proto_init() {
	if File_ResetMapRotationRegionCsReq_proto != nil {
		return
	}
	file_IJJHKDNFKMD_proto_init()
	file_MotionInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ResetMapRotationRegionCsReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetMapRotationRegionCsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ResetMapRotationRegionCsReq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ResetMapRotationRegionCsReq_proto_goTypes,
		DependencyIndexes: file_ResetMapRotationRegionCsReq_proto_depIdxs,
		MessageInfos:      file_ResetMapRotationRegionCsReq_proto_msgTypes,
	}.Build()
	File_ResetMapRotationRegionCsReq_proto = out.File
	file_ResetMapRotationRegionCsReq_proto_rawDesc = nil
	file_ResetMapRotationRegionCsReq_proto_goTypes = nil
	file_ResetMapRotationRegionCsReq_proto_depIdxs = nil
}
