// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: RogueTournFormulaInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RogueTournFormulaInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameFormulaInfo []*FormulaInfo   `protobuf:"bytes,11,rep,name=game_formula_info,json=gameFormulaInfo,proto3" json:"game_formula_info,omitempty"`
	FormulaTypeInfo *FormulaTypeInfo `protobuf:"bytes,12,opt,name=formula_type_info,json=formulaTypeInfo,proto3" json:"formula_type_info,omitempty"`
}

func (x *RogueTournFormulaInfo) Reset() {
	*x = RogueTournFormulaInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RogueTournFormulaInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RogueTournFormulaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RogueTournFormulaInfo) ProtoMessage() {}

func (x *RogueTournFormulaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_RogueTournFormulaInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RogueTournFormulaInfo.ProtoReflect.Descriptor instead.
func (*RogueTournFormulaInfo) Descriptor() ([]byte, []int) {
	return file_RogueTournFormulaInfo_proto_rawDescGZIP(), []int{0}
}

func (x *RogueTournFormulaInfo) GetGameFormulaInfo() []*FormulaInfo {
	if x != nil {
		return x.GameFormulaInfo
	}
	return nil
}

func (x *RogueTournFormulaInfo) GetFormulaTypeInfo() *FormulaTypeInfo {
	if x != nil {
		return x.FormulaTypeInfo
	}
	return nil
}

var File_RogueTournFormulaInfo_proto protoreflect.FileDescriptor

var file_RogueTournFormulaInfo_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x52, 0x6f, 0x67, 0x75, 0x65, 0x54, 0x6f, 0x75, 0x72, 0x6e, 0x46, 0x6f, 0x72, 0x6d,
	0x75, 0x6c, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x46,
	0x6f, 0x72, 0x6d, 0x75, 0x6c, 0x61, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x46, 0x6f, 0x72, 0x6d, 0x75, 0x6c, 0x61, 0x49, 0x6e, 0x66,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8f, 0x01, 0x0a, 0x15, 0x52, 0x6f, 0x67, 0x75,
	0x65, 0x54, 0x6f, 0x75, 0x72, 0x6e, 0x46, 0x6f, 0x72, 0x6d, 0x75, 0x6c, 0x61, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x38, 0x0a, 0x11, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x75, 0x6c,
	0x61, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x46,
	0x6f, 0x72, 0x6d, 0x75, 0x6c, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0f, 0x67, 0x61, 0x6d, 0x65,
	0x46, 0x6f, 0x72, 0x6d, 0x75, 0x6c, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3c, 0x0a, 0x11, 0x66,
	0x6f, 0x72, 0x6d, 0x75, 0x6c, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x75, 0x6c, 0x61,
	0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0f, 0x66, 0x6f, 0x72, 0x6d, 0x75, 0x6c,
	0x61, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x28, 0x5a, 0x08, 0x2e, 0x2f, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x1b, 0x45, 0x67, 0x67, 0x4c, 0x69, 0x6e, 0x6b, 0x2e,
	0x44, 0x61, 0x6e, 0x68, 0x65, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_RogueTournFormulaInfo_proto_rawDescOnce sync.Once
	file_RogueTournFormulaInfo_proto_rawDescData = file_RogueTournFormulaInfo_proto_rawDesc
)

func file_RogueTournFormulaInfo_proto_rawDescGZIP() []byte {
	file_RogueTournFormulaInfo_proto_rawDescOnce.Do(func() {
		file_RogueTournFormulaInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_RogueTournFormulaInfo_proto_rawDescData)
	})
	return file_RogueTournFormulaInfo_proto_rawDescData
}

var file_RogueTournFormulaInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_RogueTournFormulaInfo_proto_goTypes = []interface{}{
	(*RogueTournFormulaInfo)(nil), // 0: RogueTournFormulaInfo
	(*FormulaInfo)(nil),           // 1: FormulaInfo
	(*FormulaTypeInfo)(nil),       // 2: FormulaTypeInfo
}
var file_RogueTournFormulaInfo_proto_depIdxs = []int32{
	1, // 0: RogueTournFormulaInfo.game_formula_info:type_name -> FormulaInfo
	2, // 1: RogueTournFormulaInfo.formula_type_info:type_name -> FormulaTypeInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_RogueTournFormulaInfo_proto_init() }
func file_RogueTournFormulaInfo_proto_init() {
	if File_RogueTournFormulaInfo_proto != nil {
		return
	}
	file_FormulaTypeInfo_proto_init()
	file_FormulaInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_RogueTournFormulaInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RogueTournFormulaInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_RogueTournFormulaInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RogueTournFormulaInfo_proto_goTypes,
		DependencyIndexes: file_RogueTournFormulaInfo_proto_depIdxs,
		MessageInfos:      file_RogueTournFormulaInfo_proto_msgTypes,
	}.Build()
	File_RogueTournFormulaInfo_proto = out.File
	file_RogueTournFormulaInfo_proto_rawDesc = nil
	file_RogueTournFormulaInfo_proto_goTypes = nil
	file_RogueTournFormulaInfo_proto_depIdxs = nil
}
