// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.4.0
// source: RogueAvatarInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RogueAvatarInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AJJJNLPCEED      *CLPDAOOAHOE `protobuf:"bytes,2,opt,name=AJJJNLPCEED,proto3" json:"AJJJNLPCEED,omitempty"`
	DDDICOEFHPM      []uint32     `protobuf:"varint,7,rep,packed,name=DDDICOEFHPM,proto3" json:"DDDICOEFHPM,omitempty"`
	BaseAvatarIdList []uint32     `protobuf:"varint,11,rep,packed,name=base_avatar_id_list,json=baseAvatarIdList,proto3" json:"base_avatar_id_list,omitempty"`
	POGOCOKADMA      []uint32     `protobuf:"varint,14,rep,packed,name=POGOCOKADMA,proto3" json:"POGOCOKADMA,omitempty"`
}

func (x *RogueAvatarInfo) Reset() {
	*x = RogueAvatarInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RogueAvatarInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RogueAvatarInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RogueAvatarInfo) ProtoMessage() {}

func (x *RogueAvatarInfo) ProtoReflect() protoreflect.Message {
	mi := &file_RogueAvatarInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RogueAvatarInfo.ProtoReflect.Descriptor instead.
func (*RogueAvatarInfo) Descriptor() ([]byte, []int) {
	return file_RogueAvatarInfo_proto_rawDescGZIP(), []int{0}
}

func (x *RogueAvatarInfo) GetAJJJNLPCEED() *CLPDAOOAHOE {
	if x != nil {
		return x.AJJJNLPCEED
	}
	return nil
}

func (x *RogueAvatarInfo) GetDDDICOEFHPM() []uint32 {
	if x != nil {
		return x.DDDICOEFHPM
	}
	return nil
}

func (x *RogueAvatarInfo) GetBaseAvatarIdList() []uint32 {
	if x != nil {
		return x.BaseAvatarIdList
	}
	return nil
}

func (x *RogueAvatarInfo) GetPOGOCOKADMA() []uint32 {
	if x != nil {
		return x.POGOCOKADMA
	}
	return nil
}

type CLPDAOOAHOE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KKNMDMPJLBG uint32        `protobuf:"varint,15,opt,name=KKNMDMPJLBG,proto3" json:"KKNMDMPJLBG,omitempty"`
	PFIDJJKFGJH []uint32      `protobuf:"varint,12,rep,packed,name=PFIDJJKFGJH,proto3" json:"PFIDJJKFGJH,omitempty"`
	MGEFFLOEPBK *ItemCostList `protobuf:"bytes,7,opt,name=MGEFFLOEPBK,proto3" json:"MGEFFLOEPBK,omitempty"`
	DJGJDMBOFEH uint32        `protobuf:"varint,11,opt,name=DJGJDMBOFEH,proto3" json:"DJGJDMBOFEH,omitempty"`
}

func (x *CLPDAOOAHOE) Reset() {
	*x = CLPDAOOAHOE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RogueAvatarInfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CLPDAOOAHOE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLPDAOOAHOE) ProtoMessage() {}

func (x *CLPDAOOAHOE) ProtoReflect() protoreflect.Message {
	mi := &file_RogueAvatarInfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLPDAOOAHOE.ProtoReflect.Descriptor instead.
func (*CLPDAOOAHOE) Descriptor() ([]byte, []int) {
	return file_RogueAvatarInfo_proto_rawDescGZIP(), []int{1}
}

func (x *CLPDAOOAHOE) GetKKNMDMPJLBG() uint32 {
	if x != nil {
		return x.KKNMDMPJLBG
	}
	return 0
}

func (x *CLPDAOOAHOE) GetPFIDJJKFGJH() []uint32 {
	if x != nil {
		return x.PFIDJJKFGJH
	}
	return nil
}

func (x *CLPDAOOAHOE) GetMGEFFLOEPBK() *ItemCostList {
	if x != nil {
		return x.MGEFFLOEPBK
	}
	return nil
}

func (x *CLPDAOOAHOE) GetDJGJDMBOFEH() uint32 {
	if x != nil {
		return x.DJGJDMBOFEH
	}
	return 0
}

var File_RogueAvatarInfo_proto protoreflect.FileDescriptor

var file_RogueAvatarInfo_proto_rawDesc = []byte{
	0x0a, 0x15, 0x52, 0x6f, 0x67, 0x75, 0x65, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x73,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb4, 0x01, 0x0a, 0x0f,
	0x52, 0x6f, 0x67, 0x75, 0x65, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x2e, 0x0a, 0x0b, 0x41, 0x4a, 0x4a, 0x4a, 0x4e, 0x4c, 0x50, 0x43, 0x45, 0x45, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x43, 0x4c, 0x50, 0x44, 0x41, 0x4f, 0x4f, 0x41, 0x48,
	0x4f, 0x45, 0x52, 0x0b, 0x41, 0x4a, 0x4a, 0x4a, 0x4e, 0x4c, 0x50, 0x43, 0x45, 0x45, 0x44, 0x12,
	0x20, 0x0a, 0x0b, 0x44, 0x44, 0x44, 0x49, 0x43, 0x4f, 0x45, 0x46, 0x48, 0x50, 0x4d, 0x18, 0x07,
	0x20, 0x03, 0x28, 0x0d, 0x52, 0x0b, 0x44, 0x44, 0x44, 0x49, 0x43, 0x4f, 0x45, 0x46, 0x48, 0x50,
	0x4d, 0x12, 0x2d, 0x0a, 0x13, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x10,
	0x62, 0x61, 0x73, 0x65, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x50, 0x4f, 0x47, 0x4f, 0x43, 0x4f, 0x4b, 0x41, 0x44, 0x4d, 0x41, 0x18,
	0x0e, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0b, 0x50, 0x4f, 0x47, 0x4f, 0x43, 0x4f, 0x4b, 0x41, 0x44,
	0x4d, 0x41, 0x22, 0xa4, 0x01, 0x0a, 0x0b, 0x43, 0x4c, 0x50, 0x44, 0x41, 0x4f, 0x4f, 0x41, 0x48,
	0x4f, 0x45, 0x12, 0x20, 0x0a, 0x0b, 0x4b, 0x4b, 0x4e, 0x4d, 0x44, 0x4d, 0x50, 0x4a, 0x4c, 0x42,
	0x47, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x4b, 0x4b, 0x4e, 0x4d, 0x44, 0x4d, 0x50,
	0x4a, 0x4c, 0x42, 0x47, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x46, 0x49, 0x44, 0x4a, 0x4a, 0x4b, 0x46,
	0x47, 0x4a, 0x48, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0b, 0x50, 0x46, 0x49, 0x44, 0x4a,
	0x4a, 0x4b, 0x46, 0x47, 0x4a, 0x48, 0x12, 0x2f, 0x0a, 0x0b, 0x4d, 0x47, 0x45, 0x46, 0x46, 0x4c,
	0x4f, 0x45, 0x50, 0x42, 0x4b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x49, 0x74,
	0x65, 0x6d, 0x43, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0b, 0x4d, 0x47, 0x45, 0x46,
	0x46, 0x4c, 0x4f, 0x45, 0x50, 0x42, 0x4b, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x4a, 0x47, 0x4a, 0x44,
	0x4d, 0x42, 0x4f, 0x46, 0x45, 0x48, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x44, 0x4a,
	0x47, 0x4a, 0x44, 0x4d, 0x42, 0x4f, 0x46, 0x45, 0x48, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_RogueAvatarInfo_proto_rawDescOnce sync.Once
	file_RogueAvatarInfo_proto_rawDescData = file_RogueAvatarInfo_proto_rawDesc
)

func file_RogueAvatarInfo_proto_rawDescGZIP() []byte {
	file_RogueAvatarInfo_proto_rawDescOnce.Do(func() {
		file_RogueAvatarInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_RogueAvatarInfo_proto_rawDescData)
	})
	return file_RogueAvatarInfo_proto_rawDescData
}

var file_RogueAvatarInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_RogueAvatarInfo_proto_goTypes = []interface{}{
	(*RogueAvatarInfo)(nil), // 0: RogueAvatarInfo
	(*CLPDAOOAHOE)(nil),     // 1: CLPDAOOAHOE
	(*ItemCostList)(nil),    // 2: ItemCostList
}
var file_RogueAvatarInfo_proto_depIdxs = []int32{
	1, // 0: RogueAvatarInfo.AJJJNLPCEED:type_name -> CLPDAOOAHOE
	2, // 1: CLPDAOOAHOE.MGEFFLOEPBK:type_name -> ItemCostList
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_RogueAvatarInfo_proto_init() }
func file_RogueAvatarInfo_proto_init() {
	if File_RogueAvatarInfo_proto != nil {
		return
	}
	file_ItemCostList_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_RogueAvatarInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RogueAvatarInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RogueAvatarInfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CLPDAOOAHOE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_RogueAvatarInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RogueAvatarInfo_proto_goTypes,
		DependencyIndexes: file_RogueAvatarInfo_proto_depIdxs,
		MessageInfos:      file_RogueAvatarInfo_proto_msgTypes,
	}.Build()
	File_RogueAvatarInfo_proto = out.File
	file_RogueAvatarInfo_proto_rawDesc = nil
	file_RogueAvatarInfo_proto_goTypes = nil
	file_RogueAvatarInfo_proto_depIdxs = nil
}
