// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: SceneCastSkillCsReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SceneCastSkillCsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttackedGroupId       uint32               `protobuf:"varint,8,opt,name=attacked_group_id,json=attackedGroupId,proto3" json:"attacked_group_id,omitempty"`
	HitTargetEntityIdList []uint32             `protobuf:"varint,13,rep,packed,name=hit_target_entity_id_list,json=hitTargetEntityIdList,proto3" json:"hit_target_entity_id_list,omitempty"`
	CasterId              uint32               `protobuf:"varint,5,opt,name=caster_id,json=casterId,proto3" json:"caster_id,omitempty"`
	TargetMotion          *MotionInfo          `protobuf:"bytes,2,opt,name=target_motion,json=targetMotion,proto3" json:"target_motion,omitempty"`
	SkillIndex            uint32               `protobuf:"varint,4,opt,name=skill_index,json=skillIndex,proto3" json:"skill_index,omitempty"`
	AssistMonsterWaveList []*AssistMonsterWave `protobuf:"bytes,6,rep,name=assist_monster_wave_list,json=assistMonsterWaveList,proto3" json:"assist_monster_wave_list,omitempty"`
}

func (x *SceneCastSkillCsReq) Reset() {
	*x = SceneCastSkillCsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SceneCastSkillCsReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneCastSkillCsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneCastSkillCsReq) ProtoMessage() {}

func (x *SceneCastSkillCsReq) ProtoReflect() protoreflect.Message {
	mi := &file_SceneCastSkillCsReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneCastSkillCsReq.ProtoReflect.Descriptor instead.
func (*SceneCastSkillCsReq) Descriptor() ([]byte, []int) {
	return file_SceneCastSkillCsReq_proto_rawDescGZIP(), []int{0}
}

func (x *SceneCastSkillCsReq) GetAttackedGroupId() uint32 {
	if x != nil {
		return x.AttackedGroupId
	}
	return 0
}

func (x *SceneCastSkillCsReq) GetHitTargetEntityIdList() []uint32 {
	if x != nil {
		return x.HitTargetEntityIdList
	}
	return nil
}

func (x *SceneCastSkillCsReq) GetCasterId() uint32 {
	if x != nil {
		return x.CasterId
	}
	return 0
}

func (x *SceneCastSkillCsReq) GetTargetMotion() *MotionInfo {
	if x != nil {
		return x.TargetMotion
	}
	return nil
}

func (x *SceneCastSkillCsReq) GetSkillIndex() uint32 {
	if x != nil {
		return x.SkillIndex
	}
	return 0
}

func (x *SceneCastSkillCsReq) GetAssistMonsterWaveList() []*AssistMonsterWave {
	if x != nil {
		return x.AssistMonsterWaveList
	}
	return nil
}

var File_SceneCastSkillCsReq_proto protoreflect.FileDescriptor

var file_SceneCastSkillCsReq_proto_rawDesc = []byte{
	0x0a, 0x19, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x43, 0x61, 0x73, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c,
	0x43, 0x73, 0x52, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x4d, 0x6f, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x41,
	0x73, 0x73, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x57, 0x61, 0x76, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb8, 0x02, 0x0a, 0x13, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x43, 0x61, 0x73, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x43, 0x73, 0x52, 0x65, 0x71, 0x12, 0x2a,
	0x0a, 0x11, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x61, 0x74, 0x74, 0x61, 0x63,
	0x6b, 0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x19, 0x68, 0x69,
	0x74, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f,
	0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x15, 0x68,
	0x69, 0x74, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x61, 0x73, 0x74, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x30, 0x0a, 0x0d, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6d, 0x6f, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4d, 0x6f, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4d, 0x6f, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x4b, 0x0a, 0x18, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x5f, 0x6d,
	0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x77, 0x61, 0x76, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x73, 0x74, 0x4d,
	0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x57, 0x61, 0x76, 0x65, 0x52, 0x15, 0x61, 0x73, 0x73, 0x69,
	0x73, 0x74, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x57, 0x61, 0x76, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_SceneCastSkillCsReq_proto_rawDescOnce sync.Once
	file_SceneCastSkillCsReq_proto_rawDescData = file_SceneCastSkillCsReq_proto_rawDesc
)

func file_SceneCastSkillCsReq_proto_rawDescGZIP() []byte {
	file_SceneCastSkillCsReq_proto_rawDescOnce.Do(func() {
		file_SceneCastSkillCsReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_SceneCastSkillCsReq_proto_rawDescData)
	})
	return file_SceneCastSkillCsReq_proto_rawDescData
}

var file_SceneCastSkillCsReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SceneCastSkillCsReq_proto_goTypes = []interface{}{
	(*SceneCastSkillCsReq)(nil), // 0: SceneCastSkillCsReq
	(*MotionInfo)(nil),          // 1: MotionInfo
	(*AssistMonsterWave)(nil),   // 2: AssistMonsterWave
}
var file_SceneCastSkillCsReq_proto_depIdxs = []int32{
	1, // 0: SceneCastSkillCsReq.target_motion:type_name -> MotionInfo
	2, // 1: SceneCastSkillCsReq.assist_monster_wave_list:type_name -> AssistMonsterWave
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_SceneCastSkillCsReq_proto_init() }
func file_SceneCastSkillCsReq_proto_init() {
	if File_SceneCastSkillCsReq_proto != nil {
		return
	}
	file_MotionInfo_proto_init()
	file_AssistMonsterWave_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_SceneCastSkillCsReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SceneCastSkillCsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SceneCastSkillCsReq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SceneCastSkillCsReq_proto_goTypes,
		DependencyIndexes: file_SceneCastSkillCsReq_proto_depIdxs,
		MessageInfos:      file_SceneCastSkillCsReq_proto_msgTypes,
	}.Build()
	File_SceneCastSkillCsReq_proto = out.File
	file_SceneCastSkillCsReq_proto_rawDesc = nil
	file_SceneCastSkillCsReq_proto_goTypes = nil
	file_SceneCastSkillCsReq_proto_depIdxs = nil
}
