// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: SetRogueCollectionScRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetRogueCollectionScRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	INKHJFOPNAK []*LAOKOJAIOPD `protobuf:"bytes,6,rep,name=INKHJFOPNAK,proto3" json:"INKHJFOPNAK,omitempty"`
	Retcode     uint32         `protobuf:"varint,11,opt,name=retcode,proto3" json:"retcode,omitempty"`
	PKHKABEGPJF []*HKMBKGENKBG `protobuf:"bytes,3,rep,name=PKHKABEGPJF,proto3" json:"PKHKABEGPJF,omitempty"`
}

func (x *SetRogueCollectionScRsp) Reset() {
	*x = SetRogueCollectionScRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SetRogueCollectionScRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRogueCollectionScRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRogueCollectionScRsp) ProtoMessage() {}

func (x *SetRogueCollectionScRsp) ProtoReflect() protoreflect.Message {
	mi := &file_SetRogueCollectionScRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRogueCollectionScRsp.ProtoReflect.Descriptor instead.
func (*SetRogueCollectionScRsp) Descriptor() ([]byte, []int) {
	return file_SetRogueCollectionScRsp_proto_rawDescGZIP(), []int{0}
}

func (x *SetRogueCollectionScRsp) GetINKHJFOPNAK() []*LAOKOJAIOPD {
	if x != nil {
		return x.INKHJFOPNAK
	}
	return nil
}

func (x *SetRogueCollectionScRsp) GetRetcode() uint32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *SetRogueCollectionScRsp) GetPKHKABEGPJF() []*HKMBKGENKBG {
	if x != nil {
		return x.PKHKABEGPJF
	}
	return nil
}

var File_SetRogueCollectionScRsp_proto protoreflect.FileDescriptor

var file_SetRogueCollectionScRsp_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x53, 0x65, 0x74, 0x52, 0x6f, 0x67, 0x75, 0x65, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x63, 0x52, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x11, 0x4c, 0x41, 0x4f, 0x4b, 0x4f, 0x4a, 0x41, 0x49, 0x4f, 0x50, 0x44, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x11, 0x48, 0x4b, 0x4d, 0x42, 0x4b, 0x47, 0x45, 0x4e, 0x4b, 0x42, 0x47, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x93, 0x01, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x52, 0x6f, 0x67,
	0x75, 0x65, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x63, 0x52, 0x73,
	0x70, 0x12, 0x2e, 0x0a, 0x0b, 0x49, 0x4e, 0x4b, 0x48, 0x4a, 0x46, 0x4f, 0x50, 0x4e, 0x41, 0x4b,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4c, 0x41, 0x4f, 0x4b, 0x4f, 0x4a, 0x41,
	0x49, 0x4f, 0x50, 0x44, 0x52, 0x0b, 0x49, 0x4e, 0x4b, 0x48, 0x4a, 0x46, 0x4f, 0x50, 0x4e, 0x41,
	0x4b, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x2e, 0x0a, 0x0b, 0x50,
	0x4b, 0x48, 0x4b, 0x41, 0x42, 0x45, 0x47, 0x50, 0x4a, 0x46, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x48, 0x4b, 0x4d, 0x42, 0x4b, 0x47, 0x45, 0x4e, 0x4b, 0x42, 0x47, 0x52, 0x0b,
	0x50, 0x4b, 0x48, 0x4b, 0x41, 0x42, 0x45, 0x47, 0x50, 0x4a, 0x46, 0x42, 0x2e, 0x5a, 0x0e, 0x2e,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x1b,
	0x45, 0x67, 0x67, 0x4c, 0x69, 0x6e, 0x6b, 0x2e, 0x44, 0x61, 0x6e, 0x68, 0x65, 0x6e, 0x67, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_SetRogueCollectionScRsp_proto_rawDescOnce sync.Once
	file_SetRogueCollectionScRsp_proto_rawDescData = file_SetRogueCollectionScRsp_proto_rawDesc
)

func file_SetRogueCollectionScRsp_proto_rawDescGZIP() []byte {
	file_SetRogueCollectionScRsp_proto_rawDescOnce.Do(func() {
		file_SetRogueCollectionScRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_SetRogueCollectionScRsp_proto_rawDescData)
	})
	return file_SetRogueCollectionScRsp_proto_rawDescData
}

var file_SetRogueCollectionScRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SetRogueCollectionScRsp_proto_goTypes = []interface{}{
	(*SetRogueCollectionScRsp)(nil), // 0: SetRogueCollectionScRsp
	(*LAOKOJAIOPD)(nil),             // 1: LAOKOJAIOPD
	(*HKMBKGENKBG)(nil),             // 2: HKMBKGENKBG
}
var file_SetRogueCollectionScRsp_proto_depIdxs = []int32{
	1, // 0: SetRogueCollectionScRsp.INKHJFOPNAK:type_name -> LAOKOJAIOPD
	2, // 1: SetRogueCollectionScRsp.PKHKABEGPJF:type_name -> HKMBKGENKBG
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_SetRogueCollectionScRsp_proto_init() }
func file_SetRogueCollectionScRsp_proto_init() {
	if File_SetRogueCollectionScRsp_proto != nil {
		return
	}
	file_LAOKOJAIOPD_proto_init()
	file_HKMBKGENKBG_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_SetRogueCollectionScRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRogueCollectionScRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SetRogueCollectionScRsp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SetRogueCollectionScRsp_proto_goTypes,
		DependencyIndexes: file_SetRogueCollectionScRsp_proto_depIdxs,
		MessageInfos:      file_SetRogueCollectionScRsp_proto_msgTypes,
	}.Build()
	File_SetRogueCollectionScRsp_proto = out.File
	file_SetRogueCollectionScRsp_proto_rawDesc = nil
	file_SetRogueCollectionScRsp_proto_goTypes = nil
	file_SetRogueCollectionScRsp_proto_depIdxs = nil
}
