// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: SpaceZooDataScRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpaceZooDataScRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HPCMCALJHNA []uint32       `protobuf:"varint,1,rep,packed,name=HPCMCALJHNA,proto3" json:"HPCMCALJHNA,omitempty"`
	Retcode     uint32         `protobuf:"varint,13,opt,name=retcode,proto3" json:"retcode,omitempty"`
	GFPNBFIMCHH uint32         `protobuf:"varint,12,opt,name=GFPNBFIMCHH,proto3" json:"GFPNBFIMCHH,omitempty"`
	DLJHFIJLFHM []uint32       `protobuf:"varint,15,rep,packed,name=DLJHFIJLFHM,proto3" json:"DLJHFIJLFHM,omitempty"`
	MPMDLNNNDKD []uint32       `protobuf:"varint,8,rep,packed,name=MPMDLNNNDKD,proto3" json:"MPMDLNNNDKD,omitempty"`
	ACDNIKMDDDI []*MJNBGFIHJBN `protobuf:"bytes,10,rep,name=ACDNIKMDDDI,proto3" json:"ACDNIKMDDDI,omitempty"`
	BCNHBIGMKAJ []uint32       `protobuf:"varint,7,rep,packed,name=BCNHBIGMKAJ,proto3" json:"BCNHBIGMKAJ,omitempty"`
	HBMDPMMBCDA []*CCGFCOBHOCJ `protobuf:"bytes,9,rep,name=HBMDPMMBCDA,proto3" json:"HBMDPMMBCDA,omitempty"`
	HPCDCEKNFGH []uint32       `protobuf:"varint,14,rep,packed,name=HPCDCEKNFGH,proto3" json:"HPCDCEKNFGH,omitempty"`
}

func (x *SpaceZooDataScRsp) Reset() {
	*x = SpaceZooDataScRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SpaceZooDataScRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceZooDataScRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceZooDataScRsp) ProtoMessage() {}

func (x *SpaceZooDataScRsp) ProtoReflect() protoreflect.Message {
	mi := &file_SpaceZooDataScRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceZooDataScRsp.ProtoReflect.Descriptor instead.
func (*SpaceZooDataScRsp) Descriptor() ([]byte, []int) {
	return file_SpaceZooDataScRsp_proto_rawDescGZIP(), []int{0}
}

func (x *SpaceZooDataScRsp) GetHPCMCALJHNA() []uint32 {
	if x != nil {
		return x.HPCMCALJHNA
	}
	return nil
}

func (x *SpaceZooDataScRsp) GetRetcode() uint32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *SpaceZooDataScRsp) GetGFPNBFIMCHH() uint32 {
	if x != nil {
		return x.GFPNBFIMCHH
	}
	return 0
}

func (x *SpaceZooDataScRsp) GetDLJHFIJLFHM() []uint32 {
	if x != nil {
		return x.DLJHFIJLFHM
	}
	return nil
}

func (x *SpaceZooDataScRsp) GetMPMDLNNNDKD() []uint32 {
	if x != nil {
		return x.MPMDLNNNDKD
	}
	return nil
}

func (x *SpaceZooDataScRsp) GetACDNIKMDDDI() []*MJNBGFIHJBN {
	if x != nil {
		return x.ACDNIKMDDDI
	}
	return nil
}

func (x *SpaceZooDataScRsp) GetBCNHBIGMKAJ() []uint32 {
	if x != nil {
		return x.BCNHBIGMKAJ
	}
	return nil
}

func (x *SpaceZooDataScRsp) GetHBMDPMMBCDA() []*CCGFCOBHOCJ {
	if x != nil {
		return x.HBMDPMMBCDA
	}
	return nil
}

func (x *SpaceZooDataScRsp) GetHPCDCEKNFGH() []uint32 {
	if x != nil {
		return x.HPCDCEKNFGH
	}
	return nil
}

var File_SpaceZooDataScRsp_proto protoreflect.FileDescriptor

var file_SpaceZooDataScRsp_proto_rawDesc = []byte{
	0x0a, 0x17, 0x53, 0x70, 0x61, 0x63, 0x65, 0x5a, 0x6f, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x53, 0x63,
	0x52, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x43, 0x43, 0x47, 0x46, 0x43,
	0x4f, 0x42, 0x48, 0x4f, 0x43, 0x4a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x4d, 0x4a,
	0x4e, 0x42, 0x47, 0x46, 0x49, 0x48, 0x4a, 0x42, 0x4e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xd9, 0x02, 0x0a, 0x11, 0x53, 0x70, 0x61, 0x63, 0x65, 0x5a, 0x6f, 0x6f, 0x44, 0x61, 0x74, 0x61,
	0x53, 0x63, 0x52, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x48, 0x50, 0x43, 0x4d, 0x43, 0x41, 0x4c,
	0x4a, 0x48, 0x4e, 0x41, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0b, 0x48, 0x50, 0x43, 0x4d,
	0x43, 0x41, 0x4c, 0x4a, 0x48, 0x4e, 0x41, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x47, 0x46, 0x50, 0x4e, 0x42, 0x46, 0x49, 0x4d, 0x43, 0x48, 0x48,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x47, 0x46, 0x50, 0x4e, 0x42, 0x46, 0x49, 0x4d,
	0x43, 0x48, 0x48, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x4c, 0x4a, 0x48, 0x46, 0x49, 0x4a, 0x4c, 0x46,
	0x48, 0x4d, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0b, 0x44, 0x4c, 0x4a, 0x48, 0x46, 0x49,
	0x4a, 0x4c, 0x46, 0x48, 0x4d, 0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x50, 0x4d, 0x44, 0x4c, 0x4e, 0x4e,
	0x4e, 0x44, 0x4b, 0x44, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0b, 0x4d, 0x50, 0x4d, 0x44,
	0x4c, 0x4e, 0x4e, 0x4e, 0x44, 0x4b, 0x44, 0x12, 0x2e, 0x0a, 0x0b, 0x41, 0x43, 0x44, 0x4e, 0x49,
	0x4b, 0x4d, 0x44, 0x44, 0x44, 0x49, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4d,
	0x4a, 0x4e, 0x42, 0x47, 0x46, 0x49, 0x48, 0x4a, 0x42, 0x4e, 0x52, 0x0b, 0x41, 0x43, 0x44, 0x4e,
	0x49, 0x4b, 0x4d, 0x44, 0x44, 0x44, 0x49, 0x12, 0x20, 0x0a, 0x0b, 0x42, 0x43, 0x4e, 0x48, 0x42,
	0x49, 0x47, 0x4d, 0x4b, 0x41, 0x4a, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0b, 0x42, 0x43,
	0x4e, 0x48, 0x42, 0x49, 0x47, 0x4d, 0x4b, 0x41, 0x4a, 0x12, 0x2e, 0x0a, 0x0b, 0x48, 0x42, 0x4d,
	0x44, 0x50, 0x4d, 0x4d, 0x42, 0x43, 0x44, 0x41, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x43, 0x43, 0x47, 0x46, 0x43, 0x4f, 0x42, 0x48, 0x4f, 0x43, 0x4a, 0x52, 0x0b, 0x48, 0x42,
	0x4d, 0x44, 0x50, 0x4d, 0x4d, 0x42, 0x43, 0x44, 0x41, 0x12, 0x20, 0x0a, 0x0b, 0x48, 0x50, 0x43,
	0x44, 0x43, 0x45, 0x4b, 0x4e, 0x46, 0x47, 0x48, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0b,
	0x48, 0x50, 0x43, 0x44, 0x43, 0x45, 0x4b, 0x4e, 0x46, 0x47, 0x48, 0x42, 0x0a, 0x5a, 0x08, 0x2e,
	0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_SpaceZooDataScRsp_proto_rawDescOnce sync.Once
	file_SpaceZooDataScRsp_proto_rawDescData = file_SpaceZooDataScRsp_proto_rawDesc
)

func file_SpaceZooDataScRsp_proto_rawDescGZIP() []byte {
	file_SpaceZooDataScRsp_proto_rawDescOnce.Do(func() {
		file_SpaceZooDataScRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_SpaceZooDataScRsp_proto_rawDescData)
	})
	return file_SpaceZooDataScRsp_proto_rawDescData
}

var file_SpaceZooDataScRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SpaceZooDataScRsp_proto_goTypes = []interface{}{
	(*SpaceZooDataScRsp)(nil), // 0: SpaceZooDataScRsp
	(*MJNBGFIHJBN)(nil),       // 1: MJNBGFIHJBN
	(*CCGFCOBHOCJ)(nil),       // 2: CCGFCOBHOCJ
}
var file_SpaceZooDataScRsp_proto_depIdxs = []int32{
	1, // 0: SpaceZooDataScRsp.ACDNIKMDDDI:type_name -> MJNBGFIHJBN
	2, // 1: SpaceZooDataScRsp.HBMDPMMBCDA:type_name -> CCGFCOBHOCJ
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_SpaceZooDataScRsp_proto_init() }
func file_SpaceZooDataScRsp_proto_init() {
	if File_SpaceZooDataScRsp_proto != nil {
		return
	}
	file_CCGFCOBHOCJ_proto_init()
	file_MJNBGFIHJBN_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_SpaceZooDataScRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceZooDataScRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SpaceZooDataScRsp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SpaceZooDataScRsp_proto_goTypes,
		DependencyIndexes: file_SpaceZooDataScRsp_proto_depIdxs,
		MessageInfos:      file_SpaceZooDataScRsp_proto_msgTypes,
	}.Build()
	File_SpaceZooDataScRsp_proto = out.File
	file_SpaceZooDataScRsp_proto_rawDesc = nil
	file_SpaceZooDataScRsp_proto_goTypes = nil
	file_SpaceZooDataScRsp_proto_depIdxs = nil
}
