// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: StartMatchCsReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartMatchCsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IECMCJDHFKI FightGameMode `protobuf:"varint,1,opt,name=IECMCJDHFKI,proto3,enum=FightGameMode" json:"IECMCJDHFKI,omitempty"`
	OACBKAALIPO *LNNKGNFMMLL  `protobuf:"bytes,9,opt,name=OACBKAALIPO,proto3" json:"OACBKAALIPO,omitempty"`
}

func (x *StartMatchCsReq) Reset() {
	*x = StartMatchCsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StartMatchCsReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartMatchCsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMatchCsReq) ProtoMessage() {}

func (x *StartMatchCsReq) ProtoReflect() protoreflect.Message {
	mi := &file_StartMatchCsReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMatchCsReq.ProtoReflect.Descriptor instead.
func (*StartMatchCsReq) Descriptor() ([]byte, []int) {
	return file_StartMatchCsReq_proto_rawDescGZIP(), []int{0}
}

func (x *StartMatchCsReq) GetIECMCJDHFKI() FightGameMode {
	if x != nil {
		return x.IECMCJDHFKI
	}
	return FightGameMode_FIGHT_GAME_MODE_NONE
}

func (x *StartMatchCsReq) GetOACBKAALIPO() *LNNKGNFMMLL {
	if x != nil {
		return x.OACBKAALIPO
	}
	return nil
}

var File_StartMatchCsReq_proto protoreflect.FileDescriptor

var file_StartMatchCsReq_proto_rawDesc = []byte{
	0x0a, 0x15, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x43, 0x73, 0x52, 0x65,
	0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x46, 0x69, 0x67, 0x68, 0x74, 0x47, 0x61,
	0x6d, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x4c, 0x4e,
	0x4e, 0x4b, 0x47, 0x4e, 0x46, 0x4d, 0x4d, 0x4c, 0x4c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x73, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x43, 0x73, 0x52,
	0x65, 0x71, 0x12, 0x30, 0x0a, 0x0b, 0x49, 0x45, 0x43, 0x4d, 0x43, 0x4a, 0x44, 0x48, 0x46, 0x4b,
	0x49, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x46, 0x69, 0x67, 0x68, 0x74, 0x47,
	0x61, 0x6d, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x0b, 0x49, 0x45, 0x43, 0x4d, 0x43, 0x4a, 0x44,
	0x48, 0x46, 0x4b, 0x49, 0x12, 0x2e, 0x0a, 0x0b, 0x4f, 0x41, 0x43, 0x42, 0x4b, 0x41, 0x41, 0x4c,
	0x49, 0x50, 0x4f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4c, 0x4e, 0x4e, 0x4b,
	0x47, 0x4e, 0x46, 0x4d, 0x4d, 0x4c, 0x4c, 0x52, 0x0b, 0x4f, 0x41, 0x43, 0x42, 0x4b, 0x41, 0x41,
	0x4c, 0x49, 0x50, 0x4f, 0x42, 0x2e, 0x5a, 0x0e, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x1b, 0x45, 0x67, 0x67, 0x4c, 0x69, 0x6e, 0x6b,
	0x2e, 0x44, 0x61, 0x6e, 0x68, 0x65, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_StartMatchCsReq_proto_rawDescOnce sync.Once
	file_StartMatchCsReq_proto_rawDescData = file_StartMatchCsReq_proto_rawDesc
)

func file_StartMatchCsReq_proto_rawDescGZIP() []byte {
	file_StartMatchCsReq_proto_rawDescOnce.Do(func() {
		file_StartMatchCsReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_StartMatchCsReq_proto_rawDescData)
	})
	return file_StartMatchCsReq_proto_rawDescData
}

var file_StartMatchCsReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_StartMatchCsReq_proto_goTypes = []interface{}{
	(*StartMatchCsReq)(nil), // 0: StartMatchCsReq
	(FightGameMode)(0),      // 1: FightGameMode
	(*LNNKGNFMMLL)(nil),     // 2: LNNKGNFMMLL
}
var file_StartMatchCsReq_proto_depIdxs = []int32{
	1, // 0: StartMatchCsReq.IECMCJDHFKI:type_name -> FightGameMode
	2, // 1: StartMatchCsReq.OACBKAALIPO:type_name -> LNNKGNFMMLL
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_StartMatchCsReq_proto_init() }
func file_StartMatchCsReq_proto_init() {
	if File_StartMatchCsReq_proto != nil {
		return
	}
	file_FightGameMode_proto_init()
	file_LNNKGNFMMLL_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_StartMatchCsReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartMatchCsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_StartMatchCsReq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_StartMatchCsReq_proto_goTypes,
		DependencyIndexes: file_StartMatchCsReq_proto_depIdxs,
		MessageInfos:      file_StartMatchCsReq_proto_msgTypes,
	}.Build()
	File_StartMatchCsReq_proto = out.File
	file_StartMatchCsReq_proto_rawDesc = nil
	file_StartMatchCsReq_proto_goTypes = nil
	file_StartMatchCsReq_proto_depIdxs = nil
}
