// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: StarFightGroupInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StarFightGroupInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HardChallenged bool   `protobuf:"varint,3,opt,name=hard_challenged,json=hardChallenged,proto3" json:"hard_challenged,omitempty"`
	OEKBKACHMAB    uint32 `protobuf:"varint,13,opt,name=OEKBKACHMAB,proto3" json:"OEKBKACHMAB,omitempty"`
	FMLKGHHLNDK    uint32 `protobuf:"varint,15,opt,name=FMLKGHHLNDK,proto3" json:"FMLKGHHLNDK,omitempty"`
	GroupId        uint32 `protobuf:"varint,5,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	PLCCICHPEDE    uint32 `protobuf:"varint,7,opt,name=PLCCICHPEDE,proto3" json:"PLCCICHPEDE,omitempty"`
}

func (x *StarFightGroupInfo) Reset() {
	*x = StarFightGroupInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StarFightGroupInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StarFightGroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarFightGroupInfo) ProtoMessage() {}

func (x *StarFightGroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_StarFightGroupInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarFightGroupInfo.ProtoReflect.Descriptor instead.
func (*StarFightGroupInfo) Descriptor() ([]byte, []int) {
	return file_StarFightGroupInfo_proto_rawDescGZIP(), []int{0}
}

func (x *StarFightGroupInfo) GetHardChallenged() bool {
	if x != nil {
		return x.HardChallenged
	}
	return false
}

func (x *StarFightGroupInfo) GetOEKBKACHMAB() uint32 {
	if x != nil {
		return x.OEKBKACHMAB
	}
	return 0
}

func (x *StarFightGroupInfo) GetFMLKGHHLNDK() uint32 {
	if x != nil {
		return x.FMLKGHHLNDK
	}
	return 0
}

func (x *StarFightGroupInfo) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *StarFightGroupInfo) GetPLCCICHPEDE() uint32 {
	if x != nil {
		return x.PLCCICHPEDE
	}
	return 0
}

var File_StarFightGroupInfo_proto protoreflect.FileDescriptor

var file_StarFightGroupInfo_proto_rawDesc = []byte{
	0x0a, 0x18, 0x53, 0x74, 0x61, 0x72, 0x46, 0x69, 0x67, 0x68, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbe, 0x01, 0x0a, 0x12, 0x53,
	0x74, 0x61, 0x72, 0x46, 0x69, 0x67, 0x68, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x27, 0x0a, 0x0f, 0x68, 0x61, 0x72, 0x64, 0x5f, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65,
	0x6e, 0x67, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x68, 0x61, 0x72, 0x64,
	0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x45,
	0x4b, 0x42, 0x4b, 0x41, 0x43, 0x48, 0x4d, 0x41, 0x42, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0b, 0x4f, 0x45, 0x4b, 0x42, 0x4b, 0x41, 0x43, 0x48, 0x4d, 0x41, 0x42, 0x12, 0x20, 0x0a, 0x0b,
	0x46, 0x4d, 0x4c, 0x4b, 0x47, 0x48, 0x48, 0x4c, 0x4e, 0x44, 0x4b, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0b, 0x46, 0x4d, 0x4c, 0x4b, 0x47, 0x48, 0x48, 0x4c, 0x4e, 0x44, 0x4b, 0x12, 0x19,
	0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x4c, 0x43,
	0x43, 0x49, 0x43, 0x48, 0x50, 0x45, 0x44, 0x45, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x50, 0x4c, 0x43, 0x43, 0x49, 0x43, 0x48, 0x50, 0x45, 0x44, 0x45, 0x42, 0x2e, 0x5a, 0x0e, 0x2e,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x1b,
	0x45, 0x67, 0x67, 0x4c, 0x69, 0x6e, 0x6b, 0x2e, 0x44, 0x61, 0x6e, 0x68, 0x65, 0x6e, 0x67, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_StarFightGroupInfo_proto_rawDescOnce sync.Once
	file_StarFightGroupInfo_proto_rawDescData = file_StarFightGroupInfo_proto_rawDesc
)

func file_StarFightGroupInfo_proto_rawDescGZIP() []byte {
	file_StarFightGroupInfo_proto_rawDescOnce.Do(func() {
		file_StarFightGroupInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_StarFightGroupInfo_proto_rawDescData)
	})
	return file_StarFightGroupInfo_proto_rawDescData
}

var file_StarFightGroupInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_StarFightGroupInfo_proto_goTypes = []interface{}{
	(*StarFightGroupInfo)(nil), // 0: StarFightGroupInfo
}
var file_StarFightGroupInfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_StarFightGroupInfo_proto_init() }
func file_StarFightGroupInfo_proto_init() {
	if File_StarFightGroupInfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_StarFightGroupInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StarFightGroupInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_StarFightGroupInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_StarFightGroupInfo_proto_goTypes,
		DependencyIndexes: file_StarFightGroupInfo_proto_depIdxs,
		MessageInfos:      file_StarFightGroupInfo_proto_msgTypes,
	}.Build()
	File_StarFightGroupInfo_proto = out.File
	file_StarFightGroupInfo_proto_rawDesc = nil
	file_StarFightGroupInfo_proto_goTypes = nil
	file_StarFightGroupInfo_proto_depIdxs = nil
}
