// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: StartPunkLordRaidScRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartPunkLordRaidScRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DMEILJJDKLI int64        `protobuf:"varint,3,opt,name=DMEILJJDKLI,proto3" json:"DMEILJJDKLI,omitempty"`
	GBBBLAIEBDN bool         `protobuf:"varint,8,opt,name=GBBBLAIEBDN,proto3" json:"GBBBLAIEBDN,omitempty"`
	Retcode     uint32       `protobuf:"varint,12,opt,name=retcode,proto3" json:"retcode,omitempty"`
	NFCKEAOILDM []uint32     `protobuf:"varint,5,rep,packed,name=NFCKEAOILDM,proto3" json:"NFCKEAOILDM,omitempty"`
	Scene       *DNLBHACEIAL `protobuf:"bytes,9,opt,name=scene,proto3" json:"scene,omitempty"`
	BPGFNCNJKHH *COALHAFIPNG `protobuf:"bytes,4,opt,name=BPGFNCNJKHH,proto3" json:"BPGFNCNJKHH,omitempty"`
}

func (x *StartPunkLordRaidScRsp) Reset() {
	*x = StartPunkLordRaidScRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StartPunkLordRaidScRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartPunkLordRaidScRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPunkLordRaidScRsp) ProtoMessage() {}

func (x *StartPunkLordRaidScRsp) ProtoReflect() protoreflect.Message {
	mi := &file_StartPunkLordRaidScRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPunkLordRaidScRsp.ProtoReflect.Descriptor instead.
func (*StartPunkLordRaidScRsp) Descriptor() ([]byte, []int) {
	return file_StartPunkLordRaidScRsp_proto_rawDescGZIP(), []int{0}
}

func (x *StartPunkLordRaidScRsp) GetDMEILJJDKLI() int64 {
	if x != nil {
		return x.DMEILJJDKLI
	}
	return 0
}

func (x *StartPunkLordRaidScRsp) GetGBBBLAIEBDN() bool {
	if x != nil {
		return x.GBBBLAIEBDN
	}
	return false
}

func (x *StartPunkLordRaidScRsp) GetRetcode() uint32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *StartPunkLordRaidScRsp) GetNFCKEAOILDM() []uint32 {
	if x != nil {
		return x.NFCKEAOILDM
	}
	return nil
}

func (x *StartPunkLordRaidScRsp) GetScene() *DNLBHACEIAL {
	if x != nil {
		return x.Scene
	}
	return nil
}

func (x *StartPunkLordRaidScRsp) GetBPGFNCNJKHH() *COALHAFIPNG {
	if x != nil {
		return x.BPGFNCNJKHH
	}
	return nil
}

var File_StartPunkLordRaidScRsp_proto protoreflect.FileDescriptor

var file_StartPunkLordRaidScRsp_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x75, 0x6e, 0x6b, 0x4c, 0x6f, 0x72, 0x64, 0x52,
	0x61, 0x69, 0x64, 0x53, 0x63, 0x52, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11,
	0x43, 0x4f, 0x41, 0x4c, 0x48, 0x41, 0x46, 0x49, 0x50, 0x4e, 0x47, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x11, 0x44, 0x4e, 0x4c, 0x42, 0x48, 0x41, 0x43, 0x45, 0x49, 0x41, 0x4c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xec, 0x01, 0x0a, 0x16, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x75,
	0x6e, 0x6b, 0x4c, 0x6f, 0x72, 0x64, 0x52, 0x61, 0x69, 0x64, 0x53, 0x63, 0x52, 0x73, 0x70, 0x12,
	0x20, 0x0a, 0x0b, 0x44, 0x4d, 0x45, 0x49, 0x4c, 0x4a, 0x4a, 0x44, 0x4b, 0x4c, 0x49, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x44, 0x4d, 0x45, 0x49, 0x4c, 0x4a, 0x4a, 0x44, 0x4b, 0x4c,
	0x49, 0x12, 0x20, 0x0a, 0x0b, 0x47, 0x42, 0x42, 0x42, 0x4c, 0x41, 0x49, 0x45, 0x42, 0x44, 0x4e,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x47, 0x42, 0x42, 0x42, 0x4c, 0x41, 0x49, 0x45,
	0x42, 0x44, 0x4e, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x4e, 0x46, 0x43, 0x4b, 0x45, 0x41, 0x4f, 0x49, 0x4c, 0x44, 0x4d, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0d, 0x52, 0x0b, 0x4e, 0x46, 0x43, 0x4b, 0x45, 0x41, 0x4f, 0x49, 0x4c, 0x44, 0x4d, 0x12,
	0x22, 0x0a, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x44, 0x4e, 0x4c, 0x42, 0x48, 0x41, 0x43, 0x45, 0x49, 0x41, 0x4c, 0x52, 0x05, 0x73, 0x63,
	0x65, 0x6e, 0x65, 0x12, 0x2e, 0x0a, 0x0b, 0x42, 0x50, 0x47, 0x46, 0x4e, 0x43, 0x4e, 0x4a, 0x4b,
	0x48, 0x48, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x43, 0x4f, 0x41, 0x4c, 0x48,
	0x41, 0x46, 0x49, 0x50, 0x4e, 0x47, 0x52, 0x0b, 0x42, 0x50, 0x47, 0x46, 0x4e, 0x43, 0x4e, 0x4a,
	0x4b, 0x48, 0x48, 0x42, 0x2e, 0x5a, 0x0e, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x1b, 0x45, 0x67, 0x67, 0x4c, 0x69, 0x6e, 0x6b, 0x2e,
	0x44, 0x61, 0x6e, 0x68, 0x65, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_StartPunkLordRaidScRsp_proto_rawDescOnce sync.Once
	file_StartPunkLordRaidScRsp_proto_rawDescData = file_StartPunkLordRaidScRsp_proto_rawDesc
)

func file_StartPunkLordRaidScRsp_proto_rawDescGZIP() []byte {
	file_StartPunkLordRaidScRsp_proto_rawDescOnce.Do(func() {
		file_StartPunkLordRaidScRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_StartPunkLordRaidScRsp_proto_rawDescData)
	})
	return file_StartPunkLordRaidScRsp_proto_rawDescData
}

var file_StartPunkLordRaidScRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_StartPunkLordRaidScRsp_proto_goTypes = []interface{}{
	(*StartPunkLordRaidScRsp)(nil), // 0: StartPunkLordRaidScRsp
	(*DNLBHACEIAL)(nil),            // 1: DNLBHACEIAL
	(*COALHAFIPNG)(nil),            // 2: COALHAFIPNG
}
var file_StartPunkLordRaidScRsp_proto_depIdxs = []int32{
	1, // 0: StartPunkLordRaidScRsp.scene:type_name -> DNLBHACEIAL
	2, // 1: StartPunkLordRaidScRsp.BPGFNCNJKHH:type_name -> COALHAFIPNG
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_StartPunkLordRaidScRsp_proto_init() }
func file_StartPunkLordRaidScRsp_proto_init() {
	if File_StartPunkLordRaidScRsp_proto != nil {
		return
	}
	file_COALHAFIPNG_proto_init()
	file_DNLBHACEIAL_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_StartPunkLordRaidScRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartPunkLordRaidScRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_StartPunkLordRaidScRsp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_StartPunkLordRaidScRsp_proto_goTypes,
		DependencyIndexes: file_StartPunkLordRaidScRsp_proto_depIdxs,
		MessageInfos:      file_StartPunkLordRaidScRsp_proto_msgTypes,
	}.Build()
	File_StartPunkLordRaidScRsp_proto = out.File
	file_StartPunkLordRaidScRsp_proto_rawDesc = nil
	file_StartPunkLordRaidScRsp_proto_goTypes = nil
	file_StartPunkLordRaidScRsp_proto_depIdxs = nil
}
