// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: TakeOffRelicCsReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TakeOffRelicCsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseAvatarId  uint32   `protobuf:"varint,8,opt,name=base_avatar_id,json=baseAvatarId,proto3" json:"base_avatar_id,omitempty"`
	EquipAvatarId uint32   `protobuf:"varint,1,opt,name=equip_avatar_id,json=equipAvatarId,proto3" json:"equip_avatar_id,omitempty"`
	SlotList      []uint32 `protobuf:"varint,6,rep,packed,name=slot_list,json=slotList,proto3" json:"slot_list,omitempty"`
}

func (x *TakeOffRelicCsReq) Reset() {
	*x = TakeOffRelicCsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TakeOffRelicCsReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TakeOffRelicCsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeOffRelicCsReq) ProtoMessage() {}

func (x *TakeOffRelicCsReq) ProtoReflect() protoreflect.Message {
	mi := &file_TakeOffRelicCsReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeOffRelicCsReq.ProtoReflect.Descriptor instead.
func (*TakeOffRelicCsReq) Descriptor() ([]byte, []int) {
	return file_TakeOffRelicCsReq_proto_rawDescGZIP(), []int{0}
}

func (x *TakeOffRelicCsReq) GetBaseAvatarId() uint32 {
	if x != nil {
		return x.BaseAvatarId
	}
	return 0
}

func (x *TakeOffRelicCsReq) GetEquipAvatarId() uint32 {
	if x != nil {
		return x.EquipAvatarId
	}
	return 0
}

func (x *TakeOffRelicCsReq) GetSlotList() []uint32 {
	if x != nil {
		return x.SlotList
	}
	return nil
}

var File_TakeOffRelicCsReq_proto protoreflect.FileDescriptor

var file_TakeOffRelicCsReq_proto_rawDesc = []byte{
	0x0a, 0x17, 0x54, 0x61, 0x6b, 0x65, 0x4f, 0x66, 0x66, 0x52, 0x65, 0x6c, 0x69, 0x63, 0x43, 0x73,
	0x52, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7e, 0x0a, 0x11, 0x54, 0x61, 0x6b,
	0x65, 0x4f, 0x66, 0x66, 0x52, 0x65, 0x6c, 0x69, 0x63, 0x43, 0x73, 0x52, 0x65, 0x71, 0x12, 0x24,
	0x0a, 0x0e, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x41, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x65,
	0x71, 0x75, 0x69, 0x70, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x08, 0x73, 0x6c, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_TakeOffRelicCsReq_proto_rawDescOnce sync.Once
	file_TakeOffRelicCsReq_proto_rawDescData = file_TakeOffRelicCsReq_proto_rawDesc
)

func file_TakeOffRelicCsReq_proto_rawDescGZIP() []byte {
	file_TakeOffRelicCsReq_proto_rawDescOnce.Do(func() {
		file_TakeOffRelicCsReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_TakeOffRelicCsReq_proto_rawDescData)
	})
	return file_TakeOffRelicCsReq_proto_rawDescData
}

var file_TakeOffRelicCsReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TakeOffRelicCsReq_proto_goTypes = []interface{}{
	(*TakeOffRelicCsReq)(nil), // 0: TakeOffRelicCsReq
}
var file_TakeOffRelicCsReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_TakeOffRelicCsReq_proto_init() }
func file_TakeOffRelicCsReq_proto_init() {
	if File_TakeOffRelicCsReq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_TakeOffRelicCsReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TakeOffRelicCsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TakeOffRelicCsReq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TakeOffRelicCsReq_proto_goTypes,
		DependencyIndexes: file_TakeOffRelicCsReq_proto_depIdxs,
		MessageInfos:      file_TakeOffRelicCsReq_proto_msgTypes,
	}.Build()
	File_TakeOffRelicCsReq_proto = out.File
	file_TakeOffRelicCsReq_proto_rawDesc = nil
	file_TakeOffRelicCsReq_proto_goTypes = nil
	file_TakeOffRelicCsReq_proto_depIdxs = nil
}
