// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.4.0
// source: TextJoinQueryScRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextJoinQueryScRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TextJoinList []*TextJoinQueryScRsp_TextJoinInfo `protobuf:"bytes,4,rep,name=text_join_list,json=textJoinList,proto3" json:"text_join_list,omitempty"`
	Retcode      uint32                             `protobuf:"varint,13,opt,name=retcode,proto3" json:"retcode,omitempty"`
}

func (x *TextJoinQueryScRsp) Reset() {
	*x = TextJoinQueryScRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TextJoinQueryScRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextJoinQueryScRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextJoinQueryScRsp) ProtoMessage() {}

func (x *TextJoinQueryScRsp) ProtoReflect() protoreflect.Message {
	mi := &file_TextJoinQueryScRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextJoinQueryScRsp.ProtoReflect.Descriptor instead.
func (*TextJoinQueryScRsp) Descriptor() ([]byte, []int) {
	return file_TextJoinQueryScRsp_proto_rawDescGZIP(), []int{0}
}

func (x *TextJoinQueryScRsp) GetTextJoinList() []*TextJoinQueryScRsp_TextJoinInfo {
	if x != nil {
		return x.TextJoinList
	}
	return nil
}

func (x *TextJoinQueryScRsp) GetRetcode() uint32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

type TextJoinQueryScRsp_TextJoinInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TextItemId       uint32 `protobuf:"varint,2,opt,name=text_item_id,json=textItemId,proto3" json:"text_item_id,omitempty"`
	TextItemConfigId uint32 `protobuf:"varint,3,opt,name=text_item_config_id,json=textItemConfigId,proto3" json:"text_item_config_id,omitempty"`
}

func (x *TextJoinQueryScRsp_TextJoinInfo) Reset() {
	*x = TextJoinQueryScRsp_TextJoinInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TextJoinQueryScRsp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextJoinQueryScRsp_TextJoinInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextJoinQueryScRsp_TextJoinInfo) ProtoMessage() {}

func (x *TextJoinQueryScRsp_TextJoinInfo) ProtoReflect() protoreflect.Message {
	mi := &file_TextJoinQueryScRsp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextJoinQueryScRsp_TextJoinInfo.ProtoReflect.Descriptor instead.
func (*TextJoinQueryScRsp_TextJoinInfo) Descriptor() ([]byte, []int) {
	return file_TextJoinQueryScRsp_proto_rawDescGZIP(), []int{0, 0}
}

func (x *TextJoinQueryScRsp_TextJoinInfo) GetTextItemId() uint32 {
	if x != nil {
		return x.TextItemId
	}
	return 0
}

func (x *TextJoinQueryScRsp_TextJoinInfo) GetTextItemConfigId() uint32 {
	if x != nil {
		return x.TextItemConfigId
	}
	return 0
}

var File_TextJoinQueryScRsp_proto protoreflect.FileDescriptor

var file_TextJoinQueryScRsp_proto_rawDesc = []byte{
	0x0a, 0x18, 0x54, 0x65, 0x78, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53,
	0x63, 0x52, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd7, 0x01, 0x0a, 0x12, 0x54,
	0x65, 0x78, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x63, 0x52, 0x73,
	0x70, 0x12, 0x46, 0x0a, 0x0e, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x54, 0x65, 0x78, 0x74,
	0x4a, 0x6f, 0x69, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x63, 0x52, 0x73, 0x70, 0x2e, 0x54,
	0x65, 0x78, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x74, 0x65, 0x78,
	0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63,
	0x6f, 0x64, 0x65, 0x1a, 0x5f, 0x0a, 0x0c, 0x54, 0x65, 0x78, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x20, 0x0a, 0x0c, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x69, 0x74, 0x65, 0x6d,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74, 0x65, 0x78, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x13, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x69, 0x74,
	0x65, 0x6d, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x10, 0x74, 0x65, 0x78, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x49, 0x64, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_TextJoinQueryScRsp_proto_rawDescOnce sync.Once
	file_TextJoinQueryScRsp_proto_rawDescData = file_TextJoinQueryScRsp_proto_rawDesc
)

func file_TextJoinQueryScRsp_proto_rawDescGZIP() []byte {
	file_TextJoinQueryScRsp_proto_rawDescOnce.Do(func() {
		file_TextJoinQueryScRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_TextJoinQueryScRsp_proto_rawDescData)
	})
	return file_TextJoinQueryScRsp_proto_rawDescData
}

var file_TextJoinQueryScRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_TextJoinQueryScRsp_proto_goTypes = []interface{}{
	(*TextJoinQueryScRsp)(nil),              // 0: TextJoinQueryScRsp
	(*TextJoinQueryScRsp_TextJoinInfo)(nil), // 1: TextJoinQueryScRsp.TextJoinInfo
}
var file_TextJoinQueryScRsp_proto_depIdxs = []int32{
	1, // 0: TextJoinQueryScRsp.text_join_list:type_name -> TextJoinQueryScRsp.TextJoinInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_TextJoinQueryScRsp_proto_init() }
func file_TextJoinQueryScRsp_proto_init() {
	if File_TextJoinQueryScRsp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_TextJoinQueryScRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextJoinQueryScRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TextJoinQueryScRsp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextJoinQueryScRsp_TextJoinInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TextJoinQueryScRsp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TextJoinQueryScRsp_proto_goTypes,
		DependencyIndexes: file_TextJoinQueryScRsp_proto_depIdxs,
		MessageInfos:      file_TextJoinQueryScRsp_proto_msgTypes,
	}.Build()
	File_TextJoinQueryScRsp_proto = out.File
	file_TextJoinQueryScRsp_proto_rawDesc = nil
	file_TextJoinQueryScRsp_proto_goTypes = nil
	file_TextJoinQueryScRsp_proto_depIdxs = nil
}
